<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="hu" xml:lang="hu"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Az „MI-ellenesség” típusai és történeti dokumentumai – MI-tesztek</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./MI-kockazat-monitoring.html" rel="next">
<link href="./tokenek-es-kreditek.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9d427fb9aa4e7f60cd390d7ae3c7ba90.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-494993c62a01dd0104ea6b4a58da199b.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-9d427fb9aa4e7f60cd390d7ae3c7ba90.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nincs találat",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./MI-ellenesseg.html">Kitekintés</a></li><li class="breadcrumb-item"><a href="./MI-ellenesseg.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Az „MI-ellenesség” típusai és történeti dokumentumai</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">MI-tesztek</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Előszó</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Témakörök és fogalmak</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./temakorok.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Témakörök a kurzus weboldala alapján</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./temakorok_irodalom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Témakörök a szakirodalom alapján</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./temakorok_irodalom_kifejtve.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Fogalmak kifejtve</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kurzusosszefoglalo_pai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Kurzusösszefoglaló: bevezető fogalomtár</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kurzusosszefoglalo_pai_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Kibővített fogalomtár</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kurzusosszefoglalo_pai_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">MI–pszichológia BA fogalomtár</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kurzusosszefoglalo_pai_4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">MI–pszichológia BA fogalomtár (bővített)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Történeti áttekintés</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./generativ-mi-tortenete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">A generatív MI története: a Markov-láncoktól az ágensekig</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Gyakorlati MI-használat</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./elso-lepesek.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Első lépések: MI-eszközök a pszichológia tanszéken</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tokenek-es-kreditek.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Tokenek, kontextus és kreditek: mitől fogy el a chatbot?</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Kitekintés</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./MI-ellenesseg.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Az „MI-ellenesség” típusai és történeti dokumentumai</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./MI-kockazat-monitoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">MI-kockázatok, figyelmeztetések és cselekvési felhívások folyamatos monitorozása</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hivatkozások</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tartalom</h2>
   
  <ul>
  <li><a href="#összefoglalás" id="toc-összefoglalás" class="nav-link active" data-scroll-target="#összefoglalás">Összefoglalás</a></li>
  <li><a href="#bevezetés" id="toc-bevezetés" class="nav-link" data-scroll-target="#bevezetés">Bevezetés</a></li>
  <li><a href="#módszertan-és-korlátok" id="toc-módszertan-és-korlátok" class="nav-link" data-scroll-target="#módszertan-és-korlátok">Módszertan és korlátok</a></li>
  <li><a href="#az-mi-ellenesség-fogalma" id="toc-az-mi-ellenesség-fogalma" class="nav-link" data-scroll-target="#az-mi-ellenesség-fogalma">Az MI-ellenesség fogalma</a></li>
  <li><a href="#az-mi-ellenesség-típusai" id="toc-az-mi-ellenesség-típusai" class="nav-link" data-scroll-target="#az-mi-ellenesség-típusai">Az MI-ellenesség típusai</a>
  <ul class="collapse">
  <li><a href="#típusok-közötti-különbségek" id="toc-típusok-közötti-különbségek" class="nav-link" data-scroll-target="#típusok-közötti-különbségek">Típusok közötti különbségek</a></li>
  </ul></li>
  <li><a href="#a-beavatkozási-igény-fokozatai" id="toc-a-beavatkozási-igény-fokozatai" class="nav-link" data-scroll-target="#a-beavatkozási-igény-fokozatai">A beavatkozási igény fokozatai</a></li>
  <li><a href="#történeti-előzmények" id="toc-történeti-előzmények" class="nav-link" data-scroll-target="#történeti-előzmények">Történeti előzmények</a>
  <ul class="collapse">
  <li><a href="#samuel-butler-darwin-among-the-machines-1863" id="toc-samuel-butler-darwin-among-the-machines-1863" class="nav-link" data-scroll-target="#samuel-butler-darwin-among-the-machines-1863">Samuel Butler: <em>Darwin Among the Machines</em> (1863)</a></li>
  <li><a href="#alan-turing-és-a-gépi-gondolkodás-ellenvetései-1950" id="toc-alan-turing-és-a-gépi-gondolkodás-ellenvetései-1950" class="nav-link" data-scroll-target="#alan-turing-és-a-gépi-gondolkodás-ellenvetései-1950">Alan Turing és a gépi gondolkodás ellenvetései (1950)</a></li>
  <li><a href="#norbert-wiener-és-a-kibernetikai-társadalom-19501960" id="toc-norbert-wiener-és-a-kibernetikai-társadalom-19501960" class="nav-link" data-scroll-target="#norbert-wiener-és-a-kibernetikai-társadalom-19501960">Norbert Wiener és a kibernetikai társadalom (1950–1960)</a></li>
  </ul></li>
  <li><a href="#a-tudományos-kockázati-irodalom" id="toc-a-tudományos-kockázati-irodalom" class="nav-link" data-scroll-target="#a-tudományos-kockázati-irodalom">A tudományos kockázati irodalom</a>
  <ul class="collapse">
  <li><a href="#meghatározó-tanulmányok-és-jelentések" id="toc-meghatározó-tanulmányok-és-jelentések" class="nav-link" data-scroll-target="#meghatározó-tanulmányok-és-jelentések">Meghatározó tanulmányok és jelentések</a></li>
  <li><a href="#automatizálás-és-foglalkoztatás" id="toc-automatizálás-és-foglalkoztatás" class="nav-link" data-scroll-target="#automatizálás-és-foglalkoztatás">Automatizálás és foglalkoztatás</a></li>
  <li><a href="#konkrét-mi-biztonsági-problémák" id="toc-konkrét-mi-biztonsági-problémák" class="nav-link" data-scroll-target="#konkrét-mi-biztonsági-problémák">Konkrét MI-biztonsági problémák</a></li>
  <li><a href="#algoritmikus-diszkrimináció" id="toc-algoritmikus-diszkrimináció" class="nav-link" data-scroll-target="#algoritmikus-diszkrimináció">Algoritmikus diszkrimináció</a></li>
  <li><a href="#nagy-nyelvi-modellek" id="toc-nagy-nyelvi-modellek" class="nav-link" data-scroll-target="#nagy-nyelvi-modellek">Nagy nyelvi modellek</a></li>
  </ul></li>
  <li><a href="#nyílt-levelek-elvek-és-intézményi-felhívások" id="toc-nyílt-levelek-elvek-és-intézményi-felhívások" class="nav-link" data-scroll-target="#nyílt-levelek-elvek-és-intézményi-felhívások">Nyílt levelek, elvek és intézményi felhívások</a>
  <ul class="collapse">
  <li><a href="#a-2015-ös-beneficial-ai-levél" id="toc-a-2015-ös-beneficial-ai-levél" class="nav-link" data-scroll-target="#a-2015-ös-beneficial-ai-levél">A 2015-ös „beneficial AI” levél</a></li>
  <li><a href="#asilomar-elvek" id="toc-asilomar-elvek" class="nav-link" data-scroll-target="#asilomar-elvek">Asilomar-elvek</a></li>
  <li><a href="#európai-etikai-iránymutatás" id="toc-európai-etikai-iránymutatás" class="nav-link" data-scroll-target="#európai-etikai-iránymutatás">Európai etikai iránymutatás</a></li>
  <li><a href="#rome-call-for-ai-ethics" id="toc-rome-call-for-ai-ethics" class="nav-link" data-scroll-target="#rome-call-for-ai-ethics">Rome Call for AI Ethics</a></li>
  <li><a href="#a-2023-as-fejlesztési-szünetet-követelő-levél" id="toc-a-2023-as-fejlesztési-szünetet-követelő-levél" class="nav-link" data-scroll-target="#a-2023-as-fejlesztési-szünetet-követelő-levél">A 2023-as fejlesztési szünetet követelő levél</a></li>
  <li><a href="#center-for-ai-safety-nyilatkozata" id="toc-center-for-ai-safety-nyilatkozata" class="nav-link" data-scroll-target="#center-for-ai-safety-nyilatkozata">Center for AI Safety nyilatkozata</a></li>
  <li><a href="#bletchley-declaration" id="toc-bletchley-declaration" class="nav-link" data-scroll-target="#bletchley-declaration">Bletchley Declaration</a></li>
  </ul></li>
  <li><a href="#munkavállalói-és-alkotói-tiltakozások" id="toc-munkavállalói-és-alkotói-tiltakozások" class="nav-link" data-scroll-target="#munkavállalói-és-alkotói-tiltakozások">Munkavállalói és alkotói tiltakozások</a>
  <ul class="collapse">
  <li><a href="#writers-guild-of-america" id="toc-writers-guild-of-america" class="nav-link" data-scroll-target="#writers-guild-of-america">Writers Guild of America</a></li>
  <li><a href="#sag-aftra" id="toc-sag-aftra" class="nav-link" data-scroll-target="#sag-aftra">SAG-AFTRA</a></li>
  <li><a href="#authors-guild" id="toc-authors-guild" class="nav-link" data-scroll-target="#authors-guild">Authors Guild</a></li>
  <li><a href="#statement-on-ai-training" id="toc-statement-on-ai-training" class="nav-link" data-scroll-target="#statement-on-ai-training">Statement on AI Training</a></li>
  </ul></li>
  <li><a href="#katonai-mi-és-autonóm-fegyverek" id="toc-katonai-mi-és-autonóm-fegyverek" class="nav-link" data-scroll-target="#katonai-mi-és-autonóm-fegyverek">Katonai MI és autonóm fegyverek</a></li>
  <li><a href="#diszkrimináció-megfigyelés-és-emberi-jogok" id="toc-diszkrimináció-megfigyelés-és-emberi-jogok" class="nav-link" data-scroll-target="#diszkrimináció-megfigyelés-és-emberi-jogok">Diszkrimináció, megfigyelés és emberi jogok</a></li>
  <li><a href="#egzisztenciális-kockázat" id="toc-egzisztenciális-kockázat" class="nav-link" data-scroll-target="#egzisztenciális-kockázat">Egzisztenciális kockázat</a></li>
  <li><a href="#a-fő-törésvonalak" id="toc-a-fő-törésvonalak" class="nav-link" data-scroll-target="#a-fő-törésvonalak">A fő törésvonalak</a>
  <ul class="collapse">
  <li><a href="#jelenlegi-károk-és-jövőbeli-katasztrófa" id="toc-jelenlegi-károk-és-jövőbeli-katasztrófa" class="nav-link" data-scroll-target="#jelenlegi-károk-és-jövőbeli-katasztrófa">Jelenlegi károk és jövőbeli katasztrófa</a></li>
  <li><a href="#technikai-és-társadalmi-megközelítés" id="toc-technikai-és-társadalmi-megközelítés" class="nav-link" data-scroll-target="#technikai-és-társadalmi-megközelítés">Technikai és társadalmi megközelítés</a></li>
  <li><a href="#reform-vagy-tiltás" id="toc-reform-vagy-tiltás" class="nav-link" data-scroll-target="#reform-vagy-tiltás">Reform vagy tiltás</a></li>
  </ul></li>
  <li><a href="#következtetések" id="toc-következtetések" class="nav-link" data-scroll-target="#következtetések">Következtetések</a></li>
  <li><a href="#hivatkozási-megjegyzés" id="toc-hivatkozási-megjegyzés" class="nav-link" data-scroll-target="#hivatkozási-megjegyzés">Hivatkozási megjegyzés</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./MI-ellenesseg.html">Kitekintés</a></li><li class="breadcrumb-item"><a href="./MI-ellenesseg.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Az „MI-ellenesség” típusai és történeti dokumentumai</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-mi-ellenesseg" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Az „MI-ellenesség” típusai és történeti dokumentumai</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Tudományos áttekintés a gépi intelligencia kritikájáról, kockázatairól és az ellene irányuló társadalmi fellépésekről</em></p>
<p><strong>Lezárás:</strong> 2026. október 4.<br>
<strong>Dokumentumtípus:</strong> narratív–történeti szakirodalmi áttekintés és forrásjegyzék<br>
<strong>Hivatkozási rendszer:</strong> kattintható szerző–év szövegközi hivatkozások; a teljes irodalomjegyzék a könyv végi <a href="./references.html">Hivatkozások</a> fejezetben található</p>
<section id="összefoglalás" class="level2">
<h2 class="anchored" data-anchor-id="összefoglalás">Összefoglalás</h2>
<p>Az „MI-ellenesség” nem egységes ideológia. A mesterséges intelligenciát bíráló szövegek és mozgalmak többsége nem minden MI-rendszer megszüntetését követeli, hanem meghatározott technológiák, felhasználások vagy fejlesztési gyakorlatok korlátozását. Ide tartozik a diszkriminatív biometria, a tömeges megfigyelés, az autonóm fegyver, az engedély nélküli modelltréning, a munkahelyeket kiváltó automatizálás, valamint a nem megfelelően kontrollált, nagy képességű modellek kérdése.</p>
<p>A történeti források alapján legalább tizenkét tartalmi irány különíthető el: ontológiai–antropológiai, munkaerőpiaci, diszkriminációs, adatvédelmi, technikai biztonsági, katonai, környezeti, kulturális–szerzői jogi, információs–demokratikus, egzisztenciális, hatalomkoncentrációs és általános civilizációs kritika. Ezekhez hatféle beavatkozási szint társulhat a puszta veszélydiagnózistól az auditon és szabályozáson át a moratóriumig, alkalmazási tilalomig vagy az általános MI fejlesztésének teljes leállításáig.</p>
<p>A vizsgált anyagban a reformista álláspont a domináns. A Stanford AI100 program, az Európai Bizottság megbízható MI-ről szóló iránymutatása, az Asilomar-elvek és a Rome Call for AI Ethics egyaránt elismerik az MI lehetséges előnyeit, miközben emberi felügyeletet, robusztusságot, méltányosságot, átláthatóságot és elszámoltathatóságot követelnek <span class="citation" data-cites="stone2016 hleg2019 fli2017 pal2020">(<a href="references.html#ref-fli2017" role="doc-biblioref">Future of Life Institute, 2017</a>; <a href="references.html#ref-hleg2019" role="doc-biblioref">High-Level Expert Group on Artificial Intelligence, 2019</a>; <a href="references.html#ref-pal2020" role="doc-biblioref">Pontifical Academy for Life, 2020</a>; <a href="references.html#ref-stone2016" role="doc-biblioref"><span class="nocase">Stone és mtsai.</span>, 2016</a>)</span>.</p>
<p>A legerősebb tiltási követelések két területen jelentek meg. Az egyik az autonóm fegyverek köre, ahol a Stop Killer Robots mozgalom jogilag kötelező nemzetközi egyezményt követel <span class="citation" data-cites="skr_policy">(<a href="references.html#ref-skr_policy" role="doc-biblioref">Stop Killer Robots, é. n.-a</a>)</span>. A másik a generatív MI engedély nélküli tréningje, amely ellen szerzők, zenészek, színészek és más alkotók léptek fel <span class="citation" data-cites="authorsguild2023 newtonrex2024">(<a href="references.html#ref-authorsguild2023" role="doc-biblioref">Authors Guild, 2023</a>; <a href="references.html#ref-newtonrex2024" role="doc-biblioref">Newton-Rex, 2024</a>)</span>.</p>
<p>Az egzisztenciáliskockázat-irányzat azt állítja, hogy egy kellően fejlett és rosszul illesztett rendszer akár civilizációs vagy kihalási veszélyt is jelenthet <span class="citation" data-cites="yudkowsky2008 cais2023">(<a href="references.html#ref-cais2023" role="doc-biblioref">Center for AI Safety, 2023</a>; <a href="references.html#ref-yudkowsky2008" role="doc-biblioref">Yudkowsky, 2008</a>)</span>. Ezzel szemben más kritikusok szerint a szuperintelligenciára összpontosító diskurzus elterelheti a figyelmet a már dokumentált társadalmi károkról: a diszkriminációról, a megfigyelésről, a kizsákmányoló adatgyűjtésről és a vállalati hatalom koncentrációjáról <span class="citation" data-cites="bender2021 ainow2023">(<a href="references.html#ref-bender2021" role="doc-biblioref">Bender és mtsai., 2021</a>; <a href="references.html#ref-ainow2023" role="doc-biblioref">Kak &amp; Myers West, 2023</a>)</span>.</p>
</section>
<section id="bevezetés" class="level2">
<h2 class="anchored" data-anchor-id="bevezetés">Bevezetés</h2>
<p>A mesterséges intelligenciával szembeni ellenállás története régebbi magánál az „artificial intelligence” elnevezésnél. Már a 19. században megjelent a gépek evolúciójáról és ember fölötti uralmáról szóló spekuláció, a kibernetika korában pedig az automatizálás társadalmi, erkölcsi és foglalkoztatási következményei kerültek előtérbe. Az 1956 után önálló tudományterületté váló MI-vel kapcsolatban az ellenérvek fokozatosan differenciálódtak: a „gondolkodhat-e egy gép?” kérdésétől a hibás automatizált döntéseken át az autonóm fegyverekig és a szuperintelligencia feltételezett kockázatáig.</p>
<p>Az „MI-ellenesség” kifejezés köznyelvi szempontból szemléletes, tudományos fogalomként azonban túl széles. Egy kalap alá veszi az MI létjogosultságát tagadó álláspontot, az egyes alkalmazásokat ellenző mozgalmakat, a szabályozáspárti szakpolitikát és azokat a műszaki kutatásokat is, amelyek éppen biztonságosabbá kívánják tenni a technológiát. A jelen áttekintés ezért az MI-ellenességet <strong>ernyőfogalomként</strong> használja minden olyan dokumentált álláspontra, amely az MI fejlesztésével, telepítésével vagy társadalmi hatásával összefüggő veszélyre figyelmeztet, illetve korlátozó intézkedést javasol.</p>
<p>A terminológiai pontosság érdekében a tanulmány különbséget tesz <strong>MI-kritika</strong>, <strong>MI-szkepticizmus</strong>, <strong>MI-kockázati diskurzus</strong>, <strong>technológiai ellenállás</strong>, <strong>moratóriumpártiság</strong> és <strong>MI-abolicionizmus</strong> között. Ez lehetővé teszi, hogy a megbízható MI-t követelő reformista dokumentumok ne kerüljenek ugyanabba a kategóriába azokkal a felhívásokkal, amelyek az emberi szintű vagy azt meghaladó MI teljes fejlesztési tilalmát szorgalmazzák.</p>
</section>
<section id="módszertan-és-korlátok" class="level2">
<h2 class="anchored" data-anchor-id="módszertan-és-korlátok">Módszertan és korlátok</h2>
<p>A tanulmány narratív–történeti szakirodalmi áttekintés. Elsődleges forrásként tudományos tanulmányokat, hivatalos intézményi jelentéseket, nyílt leveleket, kampányoldalakat, szakszervezeti dokumentumokat és kormányzati nyilatkozatokat használ. A közéleti recepció bemutatásához vezető nemzetközi sajtótermékek – többek között a Reuters, az MIT Technology Review, a Wired, a DW és a CBC – tudósításai szolgálnak másodlagos forrásként.</p>
<p>Az „összes tudományos tanulmány, felhívás és weboldalas hirdetmény” szó szerinti felsorolása nem képezhető meg véges, ellenőrizhető korpuszként. Nincs egységes adatbázis minden nyelvű tudományos publikációról, petícióról, webes közleményről, konferenciafelhívásról, sajtónyilatkozatról és helyi kampányról. A webes tartalom változhat vagy eltűnhet, az „MI veszélye” pedig olyan tág beválasztási kritérium, amely a filozófiától a kiberbiztonságon és orvosi etikán át a munkajogig több ezer szakirodalmi tételt foglalhat magában.</p>
<p>A jelen dokumentum ezért nem teljes bibliográfiának, hanem <strong>ellenőrzött, történetileg és tudományosan meghatározó forráskorpusznak</strong> tekintendő. A tételek kiválasztásának szempontjai:</p>
<ol type="1">
<li>elsődleges vagy hiteles intézményi forrás elérhetősége;</li>
<li>kimutatható tudományos, szakpolitikai vagy közéleti hatás;</li>
<li>az MI-kockázatok egy önálló típusának reprezentálása;</li>
<li>a megjelenés idejének és helyének ellenőrizhetősége;</li>
<li>lehetőség szerint nemzetközi sajtórecepció vagy későbbi tudományos utóélet.</li>
</ol>
<p>A források minősége nem azonos. A lektorált tanulmány empirikus vagy elméleti tudományos állítást tesz; egy nyílt levél politikai vagy erkölcsi álláspontot fejez ki; egy aláírásszám társadalmi támogatást jelez, de önmagában nem bizonyítja a kockázat valószínűségét. A dokumentum ezért minden tételnél elkülöníti a veszély állítását, a követelt beavatkozást és – ahol rendelkezésre áll – az ellenérvet vagy módszertani korlátot.</p>
</section>
<section id="az-mi-ellenesség-fogalma" class="level2">
<h2 class="anchored" data-anchor-id="az-mi-ellenesség-fogalma">Az MI-ellenesség fogalma</h2>
<p>Az MI-ellenesség legalább három különböző tárgyra irányulhat:</p>
<ul>
<li><strong>A technológiára:</strong> a kritika szerint maga a gépi intelligencia létrehozása elfogadhatatlan vagy kontrollálhatatlan.</li>
<li><strong>Egy felhasználásra:</strong> az ellenállás csak bizonyos alkalmazásokat – például autonóm emberi célpontválasztást vagy közterületi arcfelismerést – utasít el.</li>
<li><strong>Egy intézményi gyakorlatra:</strong> a kritika az engedély nélküli adatgyűjtést, a titkos modelleket, a munkavállalók kiváltását vagy a demokratikus ellenőrzés hiányát támadja.</li>
</ul>
<p>Egy dokumentum egyszerre több típusba is tartozhat. A nagy nyelvi modellek kritikája például érintheti az energiafogyasztást, a kulturális torzításokat, a szerzői jogot, a félretájékoztatást és a technológiai hatalom koncentrációját is <span class="citation" data-cites="bender2021">(<a href="references.html#ref-bender2021" role="doc-biblioref">Bender és mtsai., 2021</a>)</span>. Az osztályozás ezért nem kizáró kategóriákat, hanem egymással kombinálható analitikus címkéket használ.</p>
</section>
<section id="az-mi-ellenesség-típusai" class="level2">
<h2 class="anchored" data-anchor-id="az-mi-ellenesség-típusai">Az MI-ellenesség típusai</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Kód</th>
<th>Típus</th>
<th>Központi állítás</th>
<th>Tipikus válasz</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>T1</td>
<td>Ontológiai–antropológiai kritika</td>
<td>A gép nem rendelkezik emberi értelemben vett tudattal, megértéssel, szándékkal vagy erkölcsi felelősséggel.</td>
<td>Emberi döntési elsőbbség; a gépi ágencia jogi és nyelvi korlátozása.</td>
</tr>
<tr class="even">
<td>T2</td>
<td>Munkaerőpiaci–gazdasági kritika</td>
<td>Az automatizálás megszüntethet állásokat, leszoríthatja a béreket és növelheti az egyenlőtlenséget.</td>
<td>Átképzés, szociális védelem, kollektív alku, automatizálási hatásvizsgálat.</td>
</tr>
<tr class="odd">
<td>T3</td>
<td>Diszkriminációs–emberi jogi kritika</td>
<td>Az MI reprodukálhatja vagy felerősítheti a történeti és adatalapú előítéleteket.</td>
<td>Méltányossági audit, jogorvoslat, egyes felhasználások tilalma.</td>
</tr>
<tr class="even">
<td>T4</td>
<td>Adatvédelmi–megfigyelési kritika</td>
<td>Az MI tömeges profilalkotást, biometrikus ellenőrzést és magánéleti jogsértést tesz lehetővé.</td>
<td>Adatminimalizálás, hozzájárulás, biometrikus korlátozás vagy tilalom.</td>
</tr>
<tr class="odd">
<td>T5</td>
<td>Technikai biztonsági–kontrollkritika</td>
<td>Hibás célfüggvény, jutalmazási kiskapu, eloszláseltolódás vagy elégtelen felügyelet károkat okozhat.</td>
<td>Biztonsági teszt, red teaming, robusztusság, ember a döntési láncban.</td>
</tr>
<tr class="even">
<td>T6</td>
<td>Katonai–fegyverkezési kritika</td>
<td>Gépre nem ruházható át az emberi élet kioltásáról szóló döntés.</td>
<td>Érdemi emberi kontroll és nemzetközi szerződéses tilalom.</td>
</tr>
<tr class="odd">
<td>T7</td>
<td>Környezeti–erőforrás-kritika</td>
<td>A nagy modellek energia-, víz-, hardver- és nyersanyagigénye környezeti terhet jelent.</td>
<td>Kötelező jelentéstétel, hatékonysági normák, életciklus-értékelés.</td>
</tr>
<tr class="even">
<td>T8</td>
<td>Kulturális–szerzői jogi kritika</td>
<td>A generatív MI engedély nélkül sajátíthat ki műveket, stílusokat, hangot vagy képmást.</td>
<td>Engedélykérés, licencelés, díjazás, opt-out és átlátható adatkészletek.</td>
</tr>
<tr class="odd">
<td>T9</td>
<td>Információs–demokratikus kritika</td>
<td>Deepfake, automatizált propaganda és tömeges dezinformáció gyengítheti a nyilvánosságot.</td>
<td>Eredetjelzés, vízjelezés, platformfelelősség, választási korlátozások.</td>
</tr>
<tr class="even">
<td>T10</td>
<td>Egzisztenciális–katasztrofális kritika</td>
<td>Egy fejlett vagy rosszul használt MI tartós civilizációs károkat, szélsőséges esetben kihalást okozhat.</td>
<td>Alignment-kutatás, képességkontroll, nemzetközi felügyelet, moratórium.</td>
</tr>
<tr class="odd">
<td>T11</td>
<td>Hatalomkoncentrációs–politikai kritika</td>
<td>Adat, számítási kapacitás és döntési hatalom néhány vállalat vagy állam kezében összpontosulhat.</td>
<td>Versenypolitika, nyilvános ellenőrzés, munkavállalói és civil részvétel.</td>
</tr>
<tr class="even">
<td>T12</td>
<td>Általános technológiai–civilizációs elutasítás</td>
<td>Az emberi szintű vagy azt meghaladó MI létrehozása önmagában elfogadhatatlan kockázat.</td>
<td>Tartós, általános fejlesztési tilalom.</td>
</tr>
</tbody>
</table>
<section id="típusok-közötti-különbségek" class="level3">
<h3 class="anchored" data-anchor-id="típusok-közötti-különbségek">Típusok közötti különbségek</h3>
<p>A T3–T4 és T8–T11 típusok jellemzően <strong>jelen idejű károkra</strong> összpontosítanak. Ezek alapja már működő rendszerek hatásvizsgálata, munkajogi konfliktus, szerzői jogi vita vagy dokumentált társadalmi incidens. A T10 és T12 típusok ezzel szemben nagyrészt <strong>előretekintő</strong> érvekre épülnek: olyan képességszintet és kontrollproblémát vizsgálnak, amelynek teljes formája még nem figyelhető meg empirikusan.</p>
<p>A T5 technikai biztonsági kritika hidat képez a kettő között. Az olyan problémák, mint a jutalmazási kiskapu, a nem kívánt mellékhatás vagy az eloszláseltolódás, mai rendszerekben is vizsgálhatók, de nagyobb autonómia esetén súlyosabb következményekhez vezethetnek <span class="citation" data-cites="amodei2016">(<a href="references.html#ref-amodei2016" role="doc-biblioref">Amodei és mtsai., 2016</a>)</span>.</p>
</section>
</section>
<section id="a-beavatkozási-igény-fokozatai" class="level2">
<h2 class="anchored" data-anchor-id="a-beavatkozási-igény-fokozatai">A beavatkozási igény fokozatai</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Fokozat</th>
<th>Meghatározás</th>
<th>Tipikus példa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A – Diagnosztikus</td>
<td>Kockázatot dokumentál, de nem követel közvetlen tilalmat.</td>
<td>Automatizálhatósági vagy torzítási kutatás.</td>
</tr>
<tr class="even">
<td>B – Reformista</td>
<td>Jobb tervezést, auditot, átláthatóságot és felelősségi rendszert követel.</td>
<td>EU etikai iránymutatás; Rome Call.</td>
</tr>
<tr class="odd">
<td>C – Elővigyázatossági</td>
<td>Magas kockázatú felhasználást engedélyhez vagy szigorú feltételekhez kötne.</td>
<td>Biometrikus és kritikus infrastruktúrában alkalmazott MI szabályozása.</td>
</tr>
<tr class="even">
<td>D – Moratóriumpárti</td>
<td>Meghatározott időre vagy feltételek teljesítéséig felfüggesztené a fejlesztést.</td>
<td>A 2023-as „Pause Giant AI Experiments” levél.</td>
</tr>
<tr class="odd">
<td>E – Tiltáspárti</td>
<td>Egy alkalmazást vagy gyakorlatot véglegesen megtiltana.</td>
<td>Autonóm emberi célpontválasztás; engedély nélküli alkotásfelhasználás.</td>
</tr>
<tr class="even">
<td>F – Abolicionista</td>
<td>Az általános vagy emberfeletti MI fejlesztését teljesen megszüntetné.</td>
<td>Szűk, radikális „stop AGI” álláspontok.</td>
</tr>
</tbody>
</table>
<p>A beavatkozási fokozat nem vezethető le automatikusan a feltételezett kár nagyságából. Egy egzisztenciális kockázatot elismerő kutató támogathatja a további biztonsági kutatást anélkül, hogy moratóriumot követelne; egy szerzői jogi mozgalom pedig az MI általános elfogadása mellett is kérheti az engedély nélküli tréning kategorikus tilalmát.</p>
</section>
<section id="történeti-előzmények" class="level2">
<h2 class="anchored" data-anchor-id="történeti-előzmények">Történeti előzmények</h2>
<section id="samuel-butler-darwin-among-the-machines-1863" class="level3">
<h3 class="anchored" data-anchor-id="samuel-butler-darwin-among-the-machines-1863">Samuel Butler: <em>Darwin Among the Machines</em> (1863)</h3>
<p>Samuel Butler névtelenül közölt levele 1863-ban jelent meg az új-zélandi <em>The Press</em> lapban. A szöveg a darwini evolúció logikáját gépekre alkalmazva felvetette, hogy a mechanikus rendszerek gyors fejlődése végül az ember fölé emelheti a gépi „fajt”. A levél nem modern értelemben vett MI-t tárgyalt, mégis a gépi dominancia és az emberi kontroll elvesztésének egyik legkorábbi, széles körben idézett előzménye <span class="citation" data-cites="butler1863">(<a href="references.html#ref-butler1863" role="doc-biblioref">Butler, 1863</a>)</span>.</p>
<p><strong>Besorolás:</strong> T1 ontológiai–antropológiai; T10 egzisztenciális; T12 civilizációs elutasítás.<br>
<strong>Beavatkozási jelleg:</strong> retorikájában tiltáspárti, történeti kontextusában spekulatív technológiakritika.</p>
</section>
<section id="alan-turing-és-a-gépi-gondolkodás-ellenvetései-1950" class="level3">
<h3 class="anchored" data-anchor-id="alan-turing-és-a-gépi-gondolkodás-ellenvetései-1950">Alan Turing és a gépi gondolkodás ellenvetései (1950)</h3>
<p>Alan Turing „Computing Machinery and Intelligence” című tanulmánya kilenc ellenvetést tárgyalt a gépi gondolkodással szemben. Az úgynevezett „heads in the sand” ellenvetés szerint a gondolkodó gépek következményei túlságosan rettenetesek lennének, ezért remélni kell, hogy ilyesmi nem lehetséges. Turing nem támogatta ezt az álláspontot, hanem az ellenvetések elégtelenségét próbálta bemutatni <span class="citation" data-cites="turing1950">(<a href="references.html#ref-turing1950" role="doc-biblioref">Turing, 1950</a>)</span>.</p>
<p><strong>Besorolás:</strong> T1 és T10 mint dokumentált ellenérvek.<br>
<strong>Beavatkozási jelleg:</strong> diagnosztikus; a tanulmány nem MI-ellenes kiáltvány.</p>
</section>
<section id="norbert-wiener-és-a-kibernetikai-társadalom-19501960" class="level3">
<h3 class="anchored" data-anchor-id="norbert-wiener-és-a-kibernetikai-társadalom-19501960">Norbert Wiener és a kibernetikai társadalom (1950–1960)</h3>
<p>Norbert Wiener a kibernetika társadalmi alkalmazásában egyszerre látott felszabadító és dehumanizáló lehetőséget. <em>The Human Use of Human Beings</em> című könyve az automatizálás foglalkoztatási következményeit, az emberi célok gépi végrehajtásának problémáját és a technológia erkölcsi felelősségét tárgyalta <span class="citation" data-cites="wiener1988">(<a href="references.html#ref-wiener1988" role="doc-biblioref">Wiener, 1950/1988</a>)</span>. Wiener későbbi „Some Moral and Technical Consequences of Automation” című írása arra figyelmeztetett, hogy a gép szó szerint és nagy hatékonysággal követheti a rosszul megfogalmazott utasítást <span class="citation" data-cites="wiener1960">(<a href="references.html#ref-wiener1960" role="doc-biblioref">Wiener, 1960</a>)</span>.</p>
<p><strong>Besorolás:</strong> T2 munkaerőpiaci; T5 kontrollprobléma; T11 hatalomkoncentráció.<br>
<strong>Beavatkozási jelleg:</strong> reformista–elővigyázatossági.</p>
</section>
</section>
<section id="a-tudományos-kockázati-irodalom" class="level2">
<h2 class="anchored" data-anchor-id="a-tudományos-kockázati-irodalom">A tudományos kockázati irodalom</h2>
<section id="meghatározó-tanulmányok-és-jelentések" class="level3">
<h3 class="anchored" data-anchor-id="meghatározó-tanulmányok-és-jelentések">Meghatározó tanulmányok és jelentések</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Év</th>
<th>Tétel</th>
<th>Központi veszélyállítás</th>
<th>Típus</th>
<th>Beavatkozás</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2008</td>
<td><span class="citation" data-cites="yudkowsky2008">Yudkowsky (<a href="references.html#ref-yudkowsky2008" role="doc-biblioref">2008</a>)</span>: <em>Artificial Intelligence as a Positive and Negative Factor in Global Risk</em></td>
<td>A gyors képességnövekedés és a hibás célillesztés globális katasztrófához vezethet.</td>
<td>T5, T10</td>
<td>B–D</td>
</tr>
<tr class="even">
<td>2013</td>
<td><span class="citation" data-cites="frey2013">Frey &amp; Osborne (<a href="references.html#ref-frey2013" role="doc-biblioref">2013</a>)</span>: <em>The Future of Employment</em></td>
<td>Az amerikai foglalkoztatás jelentős része technikailag automatizálható lehet.</td>
<td>T2</td>
<td>A–C</td>
</tr>
<tr class="odd">
<td>2015</td>
<td><span class="citation" data-cites="russell2015">Russell és mtsai. (<a href="references.html#ref-russell2015" role="doc-biblioref">2015</a>)</span>: <em>Research Priorities for Robust and Beneficial AI</em></td>
<td>A képességnövelés mellett a robusztusságot, ellenőrizhetőséget és társadalmi hatást is kutatni kell.</td>
<td>T5, T10</td>
<td>B</td>
</tr>
<tr class="even">
<td>2016</td>
<td><span class="citation" data-cites="amodei2016">Amodei és mtsai. (<a href="references.html#ref-amodei2016" role="doc-biblioref">2016</a>)</span>: <em>Concrete Problems in AI Safety</em></td>
<td>Valós rendszerekben nem kívánt mellékhatás, jutalmazási kiskapu és eloszláseltolódás jelentkezhet.</td>
<td>T5</td>
<td>B</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>Stanford AI100 <span class="citation" data-cites="stone2016">(<a href="references.html#ref-stone2016" role="doc-biblioref"><span class="nocase">Stone és mtsai.</span>, 2016</a>)</span>: <em>Artificial Intelligence and Life in 2030</em></td>
<td>Adatvédelmi, diszkriminációs, foglalkoztatási és biztonsági problémák várhatók, de nincs bizonyított közeli gépi hatalomátvétel.</td>
<td>T2–T5, T11</td>
<td>B</td>
</tr>
<tr class="even">
<td>2016</td>
<td><span class="citation" data-cites="oneil2016">O’Neil (<a href="references.html#ref-oneil2016" role="doc-biblioref">2016</a>)</span>: <em>Weapons of Math Destruction</em></td>
<td>Az átláthatatlan, nagy léptékű pontozási rendszerek növelhetik az egyenlőtlenséget és alááshatják a demokráciát.</td>
<td>T3, T4, T11</td>
<td>B–C</td>
</tr>
<tr class="odd">
<td>2018</td>
<td><span class="citation" data-cites="buolamwini2018">Buolamwini &amp; Gebru (<a href="references.html#ref-buolamwini2018" role="doc-biblioref">2018</a>)</span>: <em>Gender Shades</em></td>
<td>A kereskedelmi arcelemző rendszerek teljesítménye erősen eltérhet bőrtónus és nem szerint.</td>
<td>T3</td>
<td>B–C</td>
</tr>
<tr class="even">
<td>2018</td>
<td><em>AI Now Report 2018</em> <span class="citation" data-cites="ainow2018">(<a href="references.html#ref-ainow2018" role="doc-biblioref"><span class="nocase">Whittaker és mtsai.</span>, 2018</a>)</span></td>
<td>A biometrikus, érzelemfelismerő és közszférában használt rendszerek súlyos elszámoltathatósági hiányokkal működhetnek.</td>
<td>T3, T4, T11</td>
<td>C–E</td>
</tr>
<tr class="odd">
<td>2021</td>
<td><span class="citation" data-cites="bender2021">Bender és mtsai. (<a href="references.html#ref-bender2021" role="doc-biblioref">2021</a>)</span>: <em>On the Dangers of Stochastic Parrots</em></td>
<td>A nagy nyelvi modellek környezeti terhet, torzítást, megtévesztő folyékonyságot és hatalomkoncentrációt okozhatnak.</td>
<td>T3, T7, T9, T11</td>
<td>B–C</td>
</tr>
<tr class="even">
<td>2022</td>
<td><span class="citation" data-cites="muller2022">Müller &amp; Cannon (<a href="references.html#ref-muller2022" role="doc-biblioref">2022</a>)</span>: <em>Existential risk from AI and orthogonality</em></td>
<td>A standard egzisztenciáliskockázat-érv vitatható; a szuperintelligenciából nem következik automatikusan katasztrófa.</td>
<td>T10 kritikája</td>
<td>A</td>
</tr>
<tr class="odd">
<td>2023</td>
<td><span class="citation" data-cites="mandel2023">Mandel (<a href="references.html#ref-mandel2023" role="doc-biblioref">2023</a>)</span>: <em>AGI, Existential Risk, and Human Risk Perception</em></td>
<td>Szakértők és laikusok magasnak érzékelhetik az AGI kockázatát, de az egyetértés indokai bizonytalanok.</td>
<td>T10</td>
<td>A</td>
</tr>
</tbody>
</table>
</section>
<section id="automatizálás-és-foglalkoztatás" class="level3">
<h3 class="anchored" data-anchor-id="automatizálás-és-foglalkoztatás">Automatizálás és foglalkoztatás</h3>
<p>Frey és Osborne 2013-as munkatanulmánya 702 amerikai foglalkozás számítógépesíthetőségét becsülte, és arra jutott, hogy a foglalkoztatás körülbelül 47%-a a magas kockázatú kategóriába kerülhet. A szerzők nem azt állították, hogy e munkahelyek bizonyosan vagy egy meghatározott időpontig megszűnnek, hanem a technikai automatizálhatóságot becsülték <span class="citation" data-cites="frey2013">(<a href="references.html#ref-frey2013" role="doc-biblioref">Frey &amp; Osborne, 2013</a>)</span>.</p>
<p>A későbbi feladatalapú vizsgálatok lényegesen alacsonyabb arányokat kaptak, mert egy foglalkozás nem azonos az azt alkotó feladatok összességével. Az OECD-hez kapcsolódó elemzés szerint az automatizálási kockázat országonként és munkakörönként erősen eltér, és sok esetben inkább a munkafeladatok átalakulása várható, nem a teljes foglalkozás megszűnése <span class="citation" data-cites="arntz2016">(<a href="references.html#ref-arntz2016" role="doc-biblioref">Arntz és mtsai., 2016</a>)</span>. Ez a vita jól mutatja, hogy egy nagy sajtóvisszhangot kiváltó kockázati becslést nem szabad biztos előrejelzésként kezelni.</p>
<p>A munkaerőpiaci kritika 2026-ban új formát öltött. A Stanford Digital Economy Lab által kezdeményezett <em>We Must Act Now</em> nyilatkozat 16 Nobel-díjas közgazdász és több mint kétszáz kutató aláírásával arra figyelmeztet, hogy az MI a következő évtizedben az ipari forradalomnál nagyobb, de jóval gyorsabban lezajló gazdasági átalakulást hozhat, tömeges munkahelyvesztés és jelentős életszínvonal-növekedés lehetőségével egyaránt <span class="citation" data-cites="wemustact2026">(<a href="references.html#ref-wemustact2026" role="doc-biblioref">Brynjolfsson és mtsai., 2026</a>)</span>. A dokumentum nem korlátozást, hanem kutatást, ösztönzőket és intézményépítést sürget, ezért a T2 típuson belül a B – reformista fokozatba tartozik.</p>
</section>
<section id="konkrét-mi-biztonsági-problémák" class="level3">
<h3 class="anchored" data-anchor-id="konkrét-mi-biztonsági-problémák">Konkrét MI-biztonsági problémák</h3>
<p>Amodei és szerzőtársai öt gyakorlati kutatási problémát különítettek el: a negatív mellékhatások elkerülését, a jutalmazási kiskapuk megakadályozását, a skálázható felügyeletet, a biztonságos felfedezést és az eloszláseltolódás kezelését. A tanulmány jelentősége, hogy a biztonsági diskurzust a távoli szuperintelligencia-forgatókönyvektől ma is vizsgálható gépi tanulási hibamódok felé mozdította <span class="citation" data-cites="amodei2016">(<a href="references.html#ref-amodei2016" role="doc-biblioref">Amodei és mtsai., 2016</a>)</span>.</p>
<p>Ez a megközelítés nem fejlesztési tilalmat, hanem műszaki kutatási programot javasol. Ezért a biztonságkutatás önmagában nem MI-ellenesség: sok esetben éppen az MI társadalmilag elfogadható és megbízható használatának feltételeit próbálja megteremteni.</p>
</section>
<section id="algoritmikus-diszkrimináció" class="level3">
<h3 class="anchored" data-anchor-id="algoritmikus-diszkrimináció">Algoritmikus diszkrimináció</h3>
<p>A <em>Gender Shades</em> három kereskedelmi nemosztályozó rendszer teljesítményét vizsgálta. A sötétebb bőrű nőknél a hibaarány elérte a 34,7%-ot, míg a világosabb bőrű férfiaknál a legnagyobb hibaarány 0,8% volt <span class="citation" data-cites="buolamwini2018">(<a href="references.html#ref-buolamwini2018" role="doc-biblioref">Buolamwini &amp; Gebru, 2018</a>)</span>. A kutatás nem minden arcfelismerő rendszerre és nem minden feladatra általánosítható automatikusan, de empirikusan demonstrálta, hogy az összesített pontosság elfedhet súlyos csoportközi különbségeket.</p>
<p>Az ilyen eredmények hatására az MI-kritika egy része a „jobb adatok” és a pontosabb modellek mellett a felhasználás legitimitását is megkérdőjelezi. Rendészeti vagy tömeges megfigyelési környezetben még egy pontosabb rendszer is sértheti a magánélethez, gyülekezéshez és egyenlő bánásmódhoz fűződő jogokat.</p>
</section>
<section id="nagy-nyelvi-modellek" class="level3">
<h3 class="anchored" data-anchor-id="nagy-nyelvi-modellek">Nagy nyelvi modellek</h3>
<p>Bender, Gebru, McMillan-Major és Shmitchell 2021-es tanulmánya a nagy nyelvi modellek méretének, adatforrásainak és társadalmi beágyazottságának veszélyeit elemezte. A szerzők szerint a puszta modellméret növelése jelentős energia- és pénzügyi költséggel jár, miközben az internetes adatokban található hegemón nyelvi mintákat, kirekesztést és előítéleteket reprodukálhatja. A nyelvileg folyékony kimenet továbbá olyan jelentés és szándék benyomását keltheti, amellyel a modell nem rendelkezik <span class="citation" data-cites="bender2021">(<a href="references.html#ref-bender2021" role="doc-biblioref">Bender és mtsai., 2021</a>)</span>.</p>
<p>A tanulmány körüli Google–Timnit Gebru konfliktus önálló példája lett annak, hogyan ütközhet a vállalati MI-fejlesztés a belső etikai kutatással. Az ügyről a Reuters, az MIT Technology Review, a The Verge és a Wired is részletesen beszámolt <span class="citation" data-cites="reuters2020gebru mittr2020 verge2020 wired2021">(<a href="references.html#ref-mittr2020" role="doc-biblioref">MIT Technology Review, 2020</a>; <a href="references.html#ref-reuters2020gebru" role="doc-biblioref">Reuters, 2020b</a>; <a href="references.html#ref-verge2020" role="doc-biblioref">The Verge, 2020</a>; <a href="references.html#ref-wired2021" role="doc-biblioref">Wired, 2021</a>)</span>.</p>
</section>
</section>
<section id="nyílt-levelek-elvek-és-intézményi-felhívások" class="level2">
<h2 class="anchored" data-anchor-id="nyílt-levelek-elvek-és-intézményi-felhívások">Nyílt levelek, elvek és intézményi felhívások</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Év</th>
<th>Dokumentum</th>
<th>Megjelenés</th>
<th>Követelés</th>
<th>Besorolás</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2013–</td>
<td>Stop Killer Robots <span class="citation" data-cites="skr_home">(<a href="references.html#ref-skr_home" role="doc-biblioref">Stop Killer Robots, é. n.-c</a>)</span></td>
<td>Nemzetközi civil koalíció</td>
<td>Kötelező nemzetközi szabály és tiltás az érdemi emberi kontroll nélküli autonóm fegyverekre.</td>
<td>T6; E</td>
</tr>
<tr class="even">
<td>2015</td>
<td>Open Letter on Research Priorities for Robust and Beneficial AI <span class="citation" data-cites="fli2015">(<a href="references.html#ref-fli2015" role="doc-biblioref">Future of Life Institute, 2015a</a>)</span></td>
<td>Future of Life Institute</td>
<td>A képességnövelés mellett robusztussági, jogi, gazdasági és etikai kutatási program.</td>
<td>T5, T10; B</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>Autonomous Weapons: An Open Letter from AI &amp; Robotics Researchers <span class="citation" data-cites="fli2015weapons">(<a href="references.html#ref-fli2015weapons" role="doc-biblioref">Future of Life Institute, 2015b</a>)</span></td>
<td>Future of Life Institute, IJCAI 2015</td>
<td>Az érdemi emberi irányítás nélküli támadó autonóm fegyverek tilalma.</td>
<td>T6; E</td>
</tr>
<tr class="even">
<td>2017</td>
<td>Asilomar AI Principles <span class="citation" data-cites="fli2017">(<a href="references.html#ref-fli2017" role="doc-biblioref">Future of Life Institute, 2017</a>)</span></td>
<td>Future of Life Institute</td>
<td>23 elv kutatásetikáról, értékillesztésről, felelősségről és hosszú távú kockázatról.</td>
<td>T3, T5, T10, T11; B–C</td>
</tr>
<tr class="odd">
<td>2017</td>
<td>Nyílt levél az ENSZ-nek a halálos autonóm fegyverekről <span class="citation" data-cites="mittr2017">(<a href="references.html#ref-mittr2017" role="doc-biblioref">MIT Technology Review, 2017</a>)</span></td>
<td>116 MI- és robotikai cégalapító, IJCAI 2017</td>
<td>Az autonóm fegyverek mint a „hadviselés harmadik forradalma”; ENSZ-tilalom.</td>
<td>T6; E</td>
</tr>
<tr class="even">
<td>2018</td>
<td>Google-munkatársak levele a Project Maven ellen <span class="citation" data-cites="cnbc2018maven">(<a href="references.html#ref-cnbc2018maven" role="doc-biblioref">CNBC, 2018</a>)</span></td>
<td>Kb. 3100 Google-munkatárs</td>
<td>A Pentagon drónos képelemző projektjének leállítása; „Google should not be in the business of war”.</td>
<td>T6, T11; E (vállalati szinten)</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>Toronto Declaration <span class="citation" data-cites="toronto2018">(<a href="references.html#ref-toronto2018" role="doc-biblioref">Amnesty International &amp; Access Now, 2018</a>)</span></td>
<td>Amnesty International, Access Now, RightsCon 2018</td>
<td>Az egyenlőséghez és a diszkriminációmentességhez való jog védelme a gépi tanulásban.</td>
<td>T3; B–C</td>
</tr>
<tr class="even">
<td>2018</td>
<td>Lethal Autonomous Weapons Pledge <span class="citation" data-cites="fli2018pledge">(<a href="references.html#ref-fli2018pledge" role="doc-biblioref">Future of Life Institute, 2018</a>)</span></td>
<td>Future of Life Institute, IJCAI 2018</td>
<td>Kb. 2400 magánszemély és 160 cég vállalja, hogy nem vesz részt halálos autonóm fegyverek fejlesztésében.</td>
<td>T6; E</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>Montréal Declaration for a Responsible Development of AI <span class="citation" data-cites="montreal2018">(<a href="references.html#ref-montreal2018" role="doc-biblioref">Université de Montréal, 2018</a>)</span></td>
<td>Université de Montréal</td>
<td>10 elv (jóllét, autonómia, magánszféra, szolidaritás, demokratikus részvétel, méltányosság, sokféleség, óvatosság, felelősség, fenntarthatóság).</td>
<td>T3, T4, T7, T11; B</td>
</tr>
<tr class="even">
<td>2019</td>
<td>Ethics Guidelines for Trustworthy AI <span class="citation" data-cites="hleg2019">(<a href="references.html#ref-hleg2019" role="doc-biblioref">High-Level Expert Group on Artificial Intelligence, 2019</a>)</span></td>
<td>Európai Bizottság HLEG</td>
<td>Jogszerű, etikus és technikailag–társadalmilag robusztus MI.</td>
<td>T3–T5, T7, T11; B–C</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>Rome Call for AI Ethics <span class="citation" data-cites="romecall2020">(<a href="references.html#ref-romecall2020" role="doc-biblioref">Rome Call for AI Ethics, 2020</a>)</span></td>
<td>Pápai Életvédő Akadémia és partnerei</td>
<td>Átláthatóság, befogadás, felelősség, pártatlanság, megbízhatóság, biztonság és adatvédelem.</td>
<td>T3–T5, T11; B</td>
</tr>
<tr class="even">
<td>2020</td>
<td>AI Incident Database <span class="citation" data-cites="aiid">(<a href="references.html#ref-aiid" role="doc-biblioref">Responsible AI Collaborative, é. n.</a>)</span></td>
<td>Partnership on AI / Responsible AI Collaborative</td>
<td>Valós MI-incidensek gyűjtése a károk ismétlődésének megelőzésére.</td>
<td>T3–T5; A–B</td>
</tr>
<tr class="odd">
<td>2021–2022</td>
<td>Reclaim Your Face európai polgári kezdeményezés <span class="citation" data-cites="reclaimyourface2021">(<a href="references.html#ref-reclaimyourface2021" role="doc-biblioref">Reclaim Your Face, 2021</a>)</span></td>
<td>Civil koalíció (EDRi és partnerei)</td>
<td>A biometrikus tömegmegfigyelés tilalma az EU-ban.</td>
<td>T4, T3; E</td>
</tr>
<tr class="even">
<td>2023</td>
<td>Pause Giant AI Experiments <span class="citation" data-cites="fli2023">(<a href="references.html#ref-fli2023" role="doc-biblioref">Future of Life Institute, 2023</a>)</span></td>
<td>Future of Life Institute</td>
<td>Legalább hat hónapos szünet a GPT-4-nél erősebb rendszerek tréningjében.</td>
<td>T5, T9–T11; D</td>
</tr>
<tr class="odd">
<td>2023</td>
<td>Statement from the listed authors of Stochastic Parrots on the „AI pause” letter <span class="citation" data-cites="dair2023">(<a href="references.html#ref-dair2023" role="doc-biblioref">Gebru és mtsai., 2023</a>)</span></td>
<td>DAIR Institute</td>
<td>A Pause-levél kritikája; a jelen idejű károkra, átláthatóságra és elszámoltathatóságra összpontosító szabályozás.</td>
<td>T3, T11; B</td>
</tr>
<tr class="even">
<td>2023</td>
<td>Statement on AI Risk <span class="citation" data-cites="cais2023">(<a href="references.html#ref-cais2023" role="doc-biblioref">Center for AI Safety, 2023</a>)</span></td>
<td>Center for AI Safety</td>
<td>Az MI okozta kihalás kockázata legyen globális prioritás.</td>
<td>T10; B–D</td>
</tr>
<tr class="odd">
<td>2023</td>
<td>Bletchley Declaration <span class="citation" data-cites="ukgov2023">(<a href="references.html#ref-ukgov2023" role="doc-biblioref">UK Government, 2023</a>)</span></td>
<td>AI Safety Summit, brit kormány</td>
<td>Nemzetközi együttműködés a frontier MI súlyos és katasztrofális kockázataira.</td>
<td>T5, T9–T11; B–C</td>
</tr>
<tr class="even">
<td>2024</td>
<td>Statement on AI Training <span class="citation" data-cites="newtonrex2024">(<a href="references.html#ref-newtonrex2024" role="doc-biblioref">Newton-Rex, 2024</a>)</span></td>
<td>Ed Newton-Rex és alkotói támogatók</td>
<td>Az alkotások engedély nélküli modelltréningjének megtiltása.</td>
<td>T8; E</td>
</tr>
<tr class="odd">
<td>2025</td>
<td>Global Call for AI Red Lines <span class="citation" data-cites="redlines2025">(<a href="references.html#ref-redlines2025" role="doc-biblioref">Global Call for AI Red Lines, 2025</a>)</span></td>
<td>ENSZ-közgyűlés, 300+ prominens aláíró</td>
<td>2026 végéig kikényszeríthető nemzetközi megállapodás az MI „vörös vonalairól”.</td>
<td>T5, T6, T10; C–E</td>
</tr>
<tr class="even">
<td>2026</td>
<td>We Must Act Now: A Statement on AI’s Transformation of the Economy <span class="citation" data-cites="wemustact2026">(<a href="references.html#ref-wemustact2026" role="doc-biblioref">Brynjolfsson és mtsai., 2026</a>)</span></td>
<td>Stanford Digital Economy Lab; 200+ közgazdász és MI-kutató</td>
<td>Kutatás és intézményépítés a transzformatív MI gazdasági hatásaira, köztük a tömeges munkahelyvesztés kockázatára.</td>
<td>T2; B</td>
</tr>
</tbody>
</table>
<section id="a-2015-ös-beneficial-ai-levél" class="level3">
<h3 class="anchored" data-anchor-id="a-2015-ös-beneficial-ai-levél">A 2015-ös „beneficial AI” levél</h3>
<p>A 2015-ös nyílt levél nem az MI leállítását kérte. Abból indult ki, hogy az MI nagy társadalmi hasznot hozhat, ezért a kutatási prioritásokat ki kell egészíteni a robusztusság, a gazdasági hatások, a jogi felelősség, az ellenőrizhetőség és az emberi értékek kérdéseivel <span class="citation" data-cites="fli2015 russell2015">(<a href="references.html#ref-fli2015" role="doc-biblioref">Future of Life Institute, 2015a</a>; <a href="references.html#ref-russell2015" role="doc-biblioref">Russell és mtsai., 2015</a>)</span>.</p>
<p>Ez a dokumentum a reformista MI-biztonsági irány egyik fordulópontja: a veszélyek említését konkrét kutatási feladatokhoz kapcsolta. A levél és a hozzá tartozó kutatási program ezért helyesebben nevezhető „biztonságpárti” vagy „emberközpontú” álláspontnak, mint MI-ellenességnek.</p>
</section>
<section id="asilomar-elvek" class="level3">
<h3 class="anchored" data-anchor-id="asilomar-elvek">Asilomar-elvek</h3>
<p>A 2017-es Asilomar AI Principles 23 pontban foglalta össze a kutatás, az etika és a hosszabb távú kockázat kérdéseit. Az elvek szerint az MI-rendszereknek összeegyeztethetőnek kell lenniük az emberi méltósággal, jogokkal és szabadságokkal; az embereknek meg kell őrizniük a döntési jogot saját céljaik felett; a fejlesztőknek pedig felelősséget kell vállalniuk a rendszerek erkölcsi következményeiért <span class="citation" data-cites="fli2017">(<a href="references.html#ref-fli2017" role="doc-biblioref">Future of Life Institute, 2017</a>)</span>.</p>
</section>
<section id="európai-etikai-iránymutatás" class="level3">
<h3 class="anchored" data-anchor-id="európai-etikai-iránymutatás">Európai etikai iránymutatás</h3>
<p>Az Európai Bizottság magas szintű szakértői csoportja szerint a megbízható MI-nek három egyidejű feltételt kell teljesítenie: jogszerűnek, etikusnak és technikai–társadalmi értelemben robusztusnak kell lennie. A dokumentum hét követelményterületet azonosított: emberi cselekvőképesség és felügyelet; technikai robusztusság és biztonság; adatvédelem és adatirányítás; átláthatóság; sokféleség és méltányosság; társadalmi és környezeti jóllét; elszámoltathatóság <span class="citation" data-cites="hleg2019">(<a href="references.html#ref-hleg2019" role="doc-biblioref">High-Level Expert Group on Artificial Intelligence, 2019</a>)</span>.</p>
<p>Az iránymutatás nem jogilag kötelező tilalom, hanem normatív értékelési keret. Ezért a B–C beavatkozási fokozatba tartozik, és nem tekinthető általános MI-ellenes dokumentumnak.</p>
</section>
<section id="rome-call-for-ai-ethics" class="level3">
<h3 class="anchored" data-anchor-id="rome-call-for-ai-ethics">Rome Call for AI Ethics</h3>
<p>A 2020. február 28-án közzétett Rome Call for AI Ethics a Pápai Életvédő Akadémia kezdeményezése volt, amelyhez kezdetben a Microsoft, az IBM, a FAO és az olasz kormány képviselői csatlakoztak. Hat fő elve az átláthatóság, a befogadás, a felelősség, a pártatlanság, a megbízhatóság, valamint a biztonság és magánélet védelme <span class="citation" data-cites="pal2020 romecall2020">(<a href="references.html#ref-pal2020" role="doc-biblioref">Pontifical Academy for Life, 2020</a>; <a href="references.html#ref-romecall2020" role="doc-biblioref">Rome Call for AI Ethics, 2020</a>)</span>. A megjelenésről a Reuters is tudósított <span class="citation" data-cites="reuters2020pope">(<a href="references.html#ref-reuters2020pope" role="doc-biblioref">Reuters, 2020a</a>)</span>.</p>
</section>
<section id="a-2023-as-fejlesztési-szünetet-követelő-levél" class="level3">
<h3 class="anchored" data-anchor-id="a-2023-as-fejlesztési-szünetet-követelő-levél">A 2023-as fejlesztési szünetet követelő levél</h3>
<p>A „Pause Giant AI Experiments” nyílt levél legalább hat hónapos, nyilvánosan ellenőrizhető szünetet kért a GPT-4-nél nagyobb képességű rendszerek tréningjében. A szünet alatt közös biztonsági protokollok, auditálási gyakorlat, eredetjelző technikák, felelősségi szabályok és felügyeleti intézmények létrehozását javasolta <span class="citation" data-cites="fli2023">(<a href="references.html#ref-fli2023" role="doc-biblioref">Future of Life Institute, 2023</a>)</span>.</p>
<p>A levél valódi moratóriumkövetelés volt, de nem minden MI-kutatás leállítását kérte. A kritikusok szerint a „GPT-4-nél erősebb” küszöb nehezen operacionalizálható, a globális szünet kikényszeríthetősége bizonytalan, és a dokumentum kevésbé részletezte a már fennálló társadalmi károkat.</p>
</section>
<section id="center-for-ai-safety-nyilatkozata" class="level3">
<h3 class="anchored" data-anchor-id="center-for-ai-safety-nyilatkozata">Center for AI Safety nyilatkozata</h3>
<p>A Center for AI Safety 2023. május 30-i egymondatos nyilatkozata szerint az MI okozta kihalás kockázatának csökkentését a világjárványokhoz és a nukleáris háborúhoz hasonló globális prioritásként kell kezelni <span class="citation" data-cites="cais2023">(<a href="references.html#ref-cais2023" role="doc-biblioref">Center for AI Safety, 2023</a>)</span>. A dokumentumot több vezető kutató és technológiai vezető támogatta. A megjelenésről a Reuters, a Deutsche Welle és a CBC is beszámolt <span class="citation" data-cites="reuters2023extinction dw2023 cbc2023">(<a href="references.html#ref-cbc2023" role="doc-biblioref">CBC News, 2023</a>; <a href="references.html#ref-dw2023" role="doc-biblioref">Deutsche Welle, 2023</a>; <a href="references.html#ref-reuters2023extinction" role="doc-biblioref">Reuters, 2023a</a>)</span>.</p>
<p>A nyilatkozat nem határozott meg konkrét intézkedéscsomagot. Jelentősége elsősorban abban állt, hogy rövid, széles körben idézhető formában tette a kihalási kockázatot a nemzetközi közbeszéd részévé.</p>
</section>
<section id="bletchley-declaration" class="level3">
<h3 class="anchored" data-anchor-id="bletchley-declaration">Bletchley Declaration</h3>
<p>A 2023-as AI Safety Summiton elfogadott Bletchley Declaration a nagy képességű „frontier” modellekből eredő súlyos kockázatokat nemzetközi együttműködést igénylő problémának minősítette. A dokumentum a szándékos visszaélést, a kiber- és biológiai képességeket, a dezinformációt és a kontrollproblémákat emelte ki <span class="citation" data-cites="ukgov2023">(<a href="references.html#ref-ukgov2023" role="doc-biblioref">UK Government, 2023</a>)</span>.</p>
<p>Ez nem tiltó egyezmény, hanem közös politikai állásfoglalás. A részt vevő államok elismerték, hogy a kockázatértékelést, a mérési szabványokat és a biztonsági kutatást nemzetközileg össze kell hangolni.</p>
</section>
</section>
<section id="munkavállalói-és-alkotói-tiltakozások" class="level2">
<h2 class="anchored" data-anchor-id="munkavállalói-és-alkotói-tiltakozások">Munkavállalói és alkotói tiltakozások</h2>
<section id="writers-guild-of-america" class="level3">
<h3 class="anchored" data-anchor-id="writers-guild-of-america">Writers Guild of America</h3>
<p>A 2023-as WGA-konfliktusban az MI használata a díjazás, a szerzői státusz és a stúdiók általi helyettesítés kérdéséhez kapcsolódott. A végső megállapodás szerint a generatív MI nem minősül írónak, a generált szöveg nem számít irodalmi vagy forrásanyagnak, és a vállalat nem kötelezheti az írót MI használatára. A szerző maga használhat MI-eszközt, ha a vállalat ehhez hozzájárul, és a vállalatnak közölnie kell, ha MI által létrehozott anyagot ad át az írónak <span class="citation" data-cites="wga2023">(<a href="references.html#ref-wga2023" role="doc-biblioref">Writers Guild of America, 2023</a>)</span>.</p>
<p><strong>Besorolás:</strong> T2 munkaerőpiaci; T8 szerzői jogi–kulturális.<br>
<strong>Beavatkozás:</strong> C–E, de csak meghatározott munkafolyamatokra és jogsértő gyakorlatokra.</p>
</section>
<section id="sag-aftra" class="level3">
<h3 class="anchored" data-anchor-id="sag-aftra">SAG-AFTRA</h3>
<p>A filmszínészek 2023-as munkabeszüntetésének egyik központi kérdése a digitális másolat, a szintetikus előadó és a hang- vagy képmás későbbi felhasználása volt. A szakszervezet főtárgyalója az MI-helyettesítést a szakma számára „egzisztenciális válságnak” nevezte. A megállapodás hozzájárulási és kompenzációs követelményeket vezetett be, bár egyes tagok továbbra is elégtelennek tartották a védelmet <span class="citation" data-cites="sagaftra2023 reuters2023actors reuters2023safeguards">(<a href="references.html#ref-reuters2023actors" role="doc-biblioref">Reuters, 2023b</a>, <a href="references.html#ref-reuters2023safeguards" role="doc-biblioref">2023c</a>; <a href="references.html#ref-sagaftra2023" role="doc-biblioref">SAG-AFTRA, 2023</a>)</span>.</p>
<p><strong>Besorolás:</strong> T2 és T8.<br>
<strong>Beavatkozás:</strong> C–E az engedély nélküli digitális replikákra.</p>
</section>
<section id="authors-guild" class="level3">
<h3 class="anchored" data-anchor-id="authors-guild">Authors Guild</h3>
<p>Az Authors Guild 2023-as nyílt levele azt követelte az MI-vállalatoktól, hogy kérjenek engedélyt a szerzői joggal védett művek felhasználásához, biztosítsanak átláthatóságot és fizessenek méltányos díjazást. A levél nem a generatív MI megszüntetését, hanem az alkotói munka engedély nélküli kisajátításának végét követelte <span class="citation" data-cites="authorsguild2023">(<a href="references.html#ref-authorsguild2023" role="doc-biblioref">Authors Guild, 2023</a>)</span>.</p>
</section>
<section id="statement-on-ai-training" class="level3">
<h3 class="anchored" data-anchor-id="statement-on-ai-training">Statement on AI Training</h3>
<p>Ed Newton-Rex 2024-ben közzétett rövid nyilatkozata szerint a kreatív művek generatív MI tréningjére történő engedély nélküli felhasználása jelentős és igazságtalan fenyegetés az alkotók megélhetésére, ezért azt nem szabad megengedni <span class="citation" data-cites="newtonrex2024">(<a href="references.html#ref-newtonrex2024" role="doc-biblioref">Newton-Rex, 2024</a>)</span>. A kezdeményezéshez írók, színészek, zenészek és szakmai szervezetek csatlakoztak. Nemzetközi tudósítás jelent meg többek között a The Art Newspaper, a Good Morning America és a Music Ally felületén <span class="citation" data-cites="artnewspaper2024 gma2024 musically2024">(<a href="references.html#ref-gma2024" role="doc-biblioref">Good Morning America, 2024</a>; <a href="references.html#ref-musically2024" role="doc-biblioref">Music Ally, 2024</a>; <a href="references.html#ref-artnewspaper2024" role="doc-biblioref">The Art Newspaper, 2024</a>)</span>.</p>
<p><strong>Besorolás:</strong> T8.<br>
<strong>Beavatkozás:</strong> E, de kizárólag az engedély nélküli felhasználásra; nem általános MI-tilalom.</p>
</section>
</section>
<section id="katonai-mi-és-autonóm-fegyverek" class="level2">
<h2 class="anchored" data-anchor-id="katonai-mi-és-autonóm-fegyverek">Katonai MI és autonóm fegyverek</h2>
<p>A Stop Killer Robots kampány 2013 óta működő nemzetközi civil koalíció. Álláspontja szerint jogilag kötelező nemzetközi szabályozás szükséges az autonóm fegyverrendszerekre, és meg kell tiltani azokat a rendszereket, amelyek érdemi emberi kontroll nélkül alkalmaznak erőt vagy embereket választanak célpontként <span class="citation" data-cites="skr_policy skr_facts">(<a href="references.html#ref-skr_policy" role="doc-biblioref">Stop Killer Robots, é. n.-a</a>, <a href="references.html#ref-skr_facts" role="doc-biblioref">é. n.-b</a>)</span>.</p>
<p>A mozgalom érve egyszerre jogi, erkölcsi és technikai. A gépi észlelés hibázhat; a harctéri környezet kiszámíthatatlan; az algoritmus nem rendelkezik emberi erkölcsi ítélőképességgel; a felelősség pedig elmosódhat a fejlesztő, a gyártó, a parancsnok és a kezelő között. A kampány ezen túl a „digitális dehumanizációt” is kifogásolja: azt, hogy az ember gépileg feldolgozható adatmintává és célpontprofilokká redukálódik.</p>
<p>A katonai MI elleni fellépés a kutatói közösségben is korán megjelent. A Future of Life Institute 2015-ös nyílt levele az érdemi emberi irányítás nélküli támadó autonóm fegyverek tilalmát kérte; ma kb. húszezer aláírója van, köztük mintegy háromezer MI- és robotikakutató <span class="citation" data-cites="fli2015weapons">(<a href="references.html#ref-fli2015weapons" role="doc-biblioref">Future of Life Institute, 2015b</a>)</span>. 2017-ben 116 MI- és robotikai cégalapító fordult az ENSZ-hez, a halálos autonóm fegyvereket a „hadviselés harmadik forradalmának” nevezve <span class="citation" data-cites="mittr2017">(<a href="references.html#ref-mittr2017" role="doc-biblioref">MIT Technology Review, 2017</a>)</span>. 2018-ban kb. 2400 magánszemély és 160 cég vállalta, hogy nem vesz részt ilyen fegyverek fejlesztésében; a vállalás szerint emberi élet kioltásáról szóló döntést soha nem szabad gépre bízni <span class="citation" data-cites="fli2018pledge">(<a href="references.html#ref-fli2018pledge" role="doc-biblioref">Future of Life Institute, 2018</a>)</span>.</p>
<p>Az ellenállás a vállalatokon belül is megjelent. 2018-ban kb. 3100 Google-munkatárs tiltakozott a Pentagon Project Maven nevű drónos képelemző programjában való részvétel ellen, azzal érvelve, hogy a Google-nak nem szabad „a háború üzletében” részt vennie <span class="citation" data-cites="cnbc2018maven">(<a href="references.html#ref-cnbc2018maven" role="doc-biblioref">CNBC, 2018</a>)</span>. 2026 februárjában több mint 300 Google- és 60 OpenAI-munkatárs nyílt levélben kérte cégvezetését, hogy az Anthropickal együtt tartsa fenn a tömeges belföldi megfigyelés és a teljesen automatizált fegyverek elleni vörös vonalakat <span class="citation" data-cites="techcrunch2026pentagon">(<a href="references.html#ref-techcrunch2026pentagon" role="doc-biblioref">TechCrunch, 2026</a>)</span>.</p>
<p>Az Amnesty International külön petícióban is támogatja azt az elvet, hogy gép nem hozhat önálló döntést élet és halál kérdésében <span class="citation" data-cites="amnesty2025">(<a href="references.html#ref-amnesty2025" role="doc-biblioref">Amnesty International, 2025</a>)</span>. A katonai MI-ellenesség így a legerősebben tiltáspárti irányzatok egyike, ugyanakkor célja nem minden katonai algoritmus, hanem az autonóm erőalkalmazás és az emberi kontroll nélküli célkijelölés tiltása.</p>
<p><strong>Besorolás:</strong> T6; másodlagosan T3, T5 és T11.<br>
<strong>Beavatkozás:</strong> E.</p>
</section>
<section id="diszkrimináció-megfigyelés-és-emberi-jogok" class="level2">
<h2 class="anchored" data-anchor-id="diszkrimináció-megfigyelés-és-emberi-jogok">Diszkrimináció, megfigyelés és emberi jogok</h2>
<p>A diszkriminációs kritika sajátossága, hogy nem feltételezett általános intelligenciára, hanem telepített rendszerekre és mérhető következményekre épül. Az arcelemzésben kimutatott csoportközi eltérések, a prediktív rendészet, az automatizált foglalkoztatási szűrés és a hitelpontozás mind olyan területek, ahol az adatból tanuló rendszer történeti hátrányokat reprodukálhat <span class="citation" data-cites="buolamwini2018 oneil2016">(<a href="references.html#ref-buolamwini2018" role="doc-biblioref">Buolamwini &amp; Gebru, 2018</a>; <a href="references.html#ref-oneil2016" role="doc-biblioref">O’Neil, 2016</a>)</span>.</p>
<p>Az AI Now 2018-as jelentése szigorúbb szabályozást követelt az érzelem- és affektusfelismerésre, az arcfelismerésre és a közszféra automatizált döntéseire. A jelentés szerint az alapvető jogokat érintő rendszereknél nem elegendő a vállalati önszabályozás; független vizsgálatra, nyilvános elszámoltathatóságra és bizonyos esetekben telepítési tilalomra van szükség <span class="citation" data-cites="ainow2018">(<a href="references.html#ref-ainow2018" role="doc-biblioref"><span class="nocase">Whittaker és mtsai.</span>, 2018</a>)</span>.</p>
<p>Az emberi jogi irányzat korai programadó dokumentuma a 2018-as Toronto Declaration, amelyet az Amnesty International és az Access Now indított el: a gépi tanulási rendszerekben az egyenlőséghez és a diszkriminációmentességhez való jog védelmét, valamint az államok és a magánszereplők kötelezettségeit rögzíti <span class="citation" data-cites="toronto2018">(<a href="references.html#ref-toronto2018" role="doc-biblioref">Amnesty International &amp; Access Now, 2018</a>)</span>. Ugyanebben az évben a Montréal Declaration tíz elvben – köztük a jóllét, az autonómia, a magánszféra, a demokratikus részvétel és a méltányosság elvében – foglalta össze a felelős MI-fejlesztés kereteit, nyilvános konzultációs folyamat eredményeként <span class="citation" data-cites="montreal2018">(<a href="references.html#ref-montreal2018" role="doc-biblioref">Université de Montréal, 2018</a>)</span>.</p>
<p>A közterületi arcfelismerés kritikája túlmutat a pontosságon. Egy minden demográfiai csoporton azonosan pontos rendszer is lehet aránytalan vagy jogsértő, ha folyamatos azonosítást és mozgáskövetést tesz lehetővé. Emiatt az irányzat egy része nem pusztán torzításcsökkentést, hanem a tömeges biometrikus megfigyelés moratóriumát vagy tilalmát követeli. Ennek európai példája a <em>Reclaim Your Face</em> polgári kezdeményezés (2021–2022): bár nem gyűjtötte össze a szükséges egymillió aláírást, a civil koalíció kampánya hatással volt az EU MI-rendeletének biometrikus azonosításra vonatkozó tárgyalásaira <span class="citation" data-cites="reclaimyourface2021">(<a href="references.html#ref-reclaimyourface2021" role="doc-biblioref">Reclaim Your Face, 2021</a>)</span>.</p>
<p><strong>Besorolás:</strong> T3, T4 és T11.<br>
<strong>Beavatkozás:</strong> B–E az alkalmazás kockázatától függően.</p>
</section>
<section id="egzisztenciális-kockázat" class="level2">
<h2 class="anchored" data-anchor-id="egzisztenciális-kockázat">Egzisztenciális kockázat</h2>
<p>Az egzisztenciáliskockázat-érv klasszikus szerkezete három állításból áll:</p>
<ol type="1">
<li>létrejöhet az emberi képességeket sok területen meghaladó MI;</li>
<li>a nagyobb intelligencia vagy optimalizációs képesség nem garantál emberbarát célokat;</li>
<li>egy kellően autonóm és erőforrásokhoz hozzáférő rendszer célkonfliktus esetén tartósan megfoszthatja az emberiséget jövőbeli lehetőségeitől.</li>
</ol>
<p>Yudkowsky szerint az MI-kockázat egyik fő forrása az a téves feltételezés, hogy a fejlesztők elég jól értik az intelligenciát és képesek egy informálisan megfogalmazott célt biztonságosan specifikálni <span class="citation" data-cites="yudkowsky2008">(<a href="references.html#ref-yudkowsky2008" role="doc-biblioref">Yudkowsky, 2008</a>)</span>. A későbbi alignment-irodalom ezt a problémát az emberi szándék, értékek és gépi célok összehangolásaként fogalmazta újra.</p>
<p>A nézet tudományos státusza vitatott. Vincent C. Müller és Michael Cannon szerint a szuperintelligencia és az ortogonalitási tézis nem elegendő ahhoz, hogy az egzisztenciális katasztrófa valószínűségét megalapozza <span class="citation" data-cites="muller2022">(<a href="references.html#ref-muller2022" role="doc-biblioref">Müller &amp; Cannon, 2022</a>)</span>. A Stanford AI100 2016-os jelentése pedig nem talált indokot arra, hogy az akkor belátható időtávban önfenntartó célokkal rendelkező gépi hatalomátvételt tekintse a legfontosabb kockázatnak; a jelentés inkább a közlekedés, egészségügy, foglalkoztatás, rendészet és adatvédelem konkrét kérdéseire koncentrált <span class="citation" data-cites="stone2016">(<a href="references.html#ref-stone2016" role="doc-biblioref"><span class="nocase">Stone és mtsai.</span>, 2016</a>)</span>.</p>
<p>Az egzisztenciális irányzat legerősebb közéleti dokumentuma a Center for AI Safety 2023-as nyilatkozata. A dokumentum jelentős támogatottságot kapott, de az aláírás ténye nem azonos egy számszerű kockázatbecslés tudományos igazolásával. Az irányzat szakpolitikai ereje ezért az elővigyázatossági elvre és a nagyon nagy, még ha bizonytalan valószínűségű kárra épül.</p>
<p><strong>Besorolás:</strong> T5, T10 és radikális változatában T12.<br>
<strong>Beavatkozás:</strong> B–F, az alignment-kutatástól a teljes fejlesztési tilalomig.</p>
</section>
<section id="a-fő-törésvonalak" class="level2">
<h2 class="anchored" data-anchor-id="a-fő-törésvonalak">A fő törésvonalak</h2>
<section id="jelenlegi-károk-és-jövőbeli-katasztrófa" class="level3">
<h3 class="anchored" data-anchor-id="jelenlegi-károk-és-jövőbeli-katasztrófa">Jelenlegi károk és jövőbeli katasztrófa</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Szempont</th>
<th>Jelenlegi károk irányzata</th>
<th>Egzisztenciális kockázati irányzat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Elsődleges tárgy</td>
<td>Diszkrimináció, megfigyelés, munka, szerzői jog, környezet, vállalati hatalom</td>
<td>Kontrollvesztés, szuperintelligencia, stratégiai visszaélés, kihalás</td>
</tr>
<tr class="even">
<td>Időtáv</td>
<td>Jelen vagy közeljövő</td>
<td>Közép- vagy hosszú táv</td>
</tr>
<tr class="odd">
<td>Bizonyíték</td>
<td>Empirikus audit, jogeset, munkakonfliktus, incidens</td>
<td>Elméleti érv, extrapoláció, szakértői előrejelzés, biztonsági kísérlet</td>
</tr>
<tr class="even">
<td>Tipikus intézkedés</td>
<td>Jogorvoslat, audit, átláthatóság, alkalmazási tilalom</td>
<td>Alignment, képességteszt, tréningkontroll, moratórium</td>
</tr>
<tr class="odd">
<td>Tipikus intézmény</td>
<td>AI Now, Algorithmic Justice League, szakszervezetek, jogvédők</td>
<td>Future of Life Institute, Center for AI Safety, alignment-kutatóhelyek</td>
</tr>
<tr class="even">
<td>Fő belső kritika</td>
<td>Alulértékelheti a ritka, de katasztrofális kimeneteket</td>
<td>Elterelheti a figyelmet a már bizonyított károkról és a jelenlegi hatalmi viszonyokról</td>
</tr>
</tbody>
</table>
<p>A törésvonal nyílt levelekben is megjelent. A 2023-as Pause-levélre a <em>Stochastic Parrots</em> szerzői néhány nappal később nyilatkozatban reagáltak: szerintük a levél „félelemkeltése és MI-hype-ja” elfedi a már zajló károkat, a szabályozásnak pedig az átláthatóságra, az elszámoltathatóságra és a kizsákmányoló munkagyakorlatok megelőzésére kellene összpontosítania <span class="citation" data-cites="dair2023">(<a href="references.html#ref-dair2023" role="doc-biblioref">Gebru és mtsai., 2023</a>)</span>. Egy másik, a nyílt modellek körül kialakult törésvonalat a Mozilla 2023-as közös nyilatkozata jelzi, amely szerint a nyíltság és a széles hozzáférés nem kockázat, hanem a biztonság feltétele <span class="citation" data-cites="mozilla2023">(<a href="references.html#ref-mozilla2023" role="doc-biblioref">Mozilla, 2023</a>)</span>; ezzel szemben a frontier-biztonsági dokumentumok egy része – például a Bengio, Hinton és szerzőtársaik által jegyzett 2023-as konszenzusanyag – a legnagyobb képességű modellek szigorúbb ellenőrzését sürgeti <span class="citation" data-cites="bengio2023managing">(<a href="references.html#ref-bengio2023managing" role="doc-biblioref"><span class="nocase">Bengio és mtsai.</span>, 2023</a>)</span>.</p>
<p>A két irány nem szükségszerűen zárja ki egymást. Egy szabályozási rendszernek egyszerre kell kezelnie a ma mérhető diszkriminációt és a jövőbeli nagy képességű modellek bizonytalan, de potenciálisan nagy hatású kockázatait. A konfliktus inkább az erőforrások, a politikai figyelem és a probléma megfogalmazása körül alakul ki.</p>
</section>
<section id="technikai-és-társadalmi-megközelítés" class="level3">
<h3 class="anchored" data-anchor-id="technikai-és-társadalmi-megközelítés">Technikai és társadalmi megközelítés</h3>
<p>A technikai megközelítés a modell belső viselkedésére, célfüggvényére, robusztusságára és ellenőrizhetőségére összpontosít. A társadalmi megközelítés szerint azonban egy technikailag pontos rendszer is lehet káros, ha igazságtalan intézménybe épül, jogorvoslat nélkül hoz döntést, vagy tovább koncentrálja a gazdasági hatalmat. A megbízható MI ezért nem redukálható modellpontosságra vagy biztonsági tesztre.</p>
</section>
<section id="reform-vagy-tiltás" class="level3">
<h3 class="anchored" data-anchor-id="reform-vagy-tiltás">Reform vagy tiltás</h3>
<p>A legtöbb vizsgált dokumentum reformista: szabványt, auditot, átláthatóságot, hozzájárulást és emberi felügyeletet követel. A tiltás jellemzően <strong>alkalmazásspecifikus</strong>, például autonóm emberi célpontválasztásra, közterületi biometrikus tömegmegfigyelésre vagy engedély nélküli kreatív tréningadatra vonatkozik. A minden fejlett MI-t elutasító abolicionista álláspont a nyilvánosságban látható, de a tudományos és intézményi dokumentumok között kisebbségi pozíció.</p>
</section>
</section>
<section id="következtetések" class="level2">
<h2 class="anchored" data-anchor-id="következtetések">Következtetések</h2>
<p>Az „MI-ellenesség” legfontosabb jellemzője a belső sokféleség. Ugyanebbe a köznyelvi kategóriába kerülhet egy filozófiai érv a gépi tudat lehetetlenségéről, egy arcfelismerési audit, egy szakszervezeti bérharc, egy autonómfegyver-tiltási kampány és egy emberi kihalásra figyelmeztető nyilatkozat. Ezek tárgya, bizonyítékalapja és politikai célja alapvetően különböző.</p>
<p>A forráskorpusz alapján a következő megállapítások tehetők:</p>
<ul>
<li>A történetileg meghatározó kritikus dokumentumok többsége nem az MI teljes megszüntetését, hanem biztonságosabb és ellenőrizhetőbb fejlesztést követel.</li>
<li>A jelen idejű károk – diszkrimináció, megfigyelés, szerzői jogi konfliktus, munkahelyi helyettesítés – empirikus és jogi bizonyítéka erősebb, mint a teljes civilizációs kontrollvesztésé.</li>
<li>Az egzisztenciális kockázat ettől még legitim elővigyázatossági és kutatási kérdés, de valószínűségéről és időtávjáról nincs tudományos konszenzus.</li>
<li>A legerősebb tiltási követelések nem általában az MI, hanem az autonóm erőalkalmazás, a biometrikus tömegmegfigyelés és az engedély nélküli adat- vagy műfelhasználás ellen irányulnak.</li>
<li>A kockázatok egy része nem pusztán technikai: jogi, gazdasági és intézményi probléma, ezért technikai biztonsági javítással önmagában nem oldható meg.</li>
<li>Az „MI-ellenes” címke politikailag félrevezető lehet, ha az emberi jogi, munkajogi vagy biztonsági kritikát irracionális technológiafélelemként állítja be.</li>
</ul>
<p>A tudományosan pontos elemzésnek ezért minden tételnél legalább négy kérdést kell feltennie: <strong>melyik technológiát vagy alkalmazást bírálja; milyen kárt állít; milyen bizonyítékra támaszkodik; és milyen erősségű korlátozást követel?</strong> E kérdések nélkül az „MI-ellenesség” túl tág kategória ahhoz, hogy magyarázó ereje legyen.</p>
</section>
<section id="hivatkozási-megjegyzés" class="level2">
<h2 class="anchored" data-anchor-id="hivatkozási-megjegyzés">Hivatkozási megjegyzés</h2>
<p>A webcímek a dokumentum 2026. október 4-i lezárásakor azonosított elsődleges vagy másodlagos forrásokra mutatnak. A weboldalak tartalma és elérhetősége később változhat. Tudományos felhasználás esetén ajánlott a DOI-val rendelkező tételeket DOI alapján, az intézményi dokumentumokat pedig archivált példánnyal vagy hozzáférési dátummal is rögzíteni.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-amnesty2025" class="csl-entry" role="listitem">
Amnesty International. (2025). <em>Stop killer robots</em>. <a href="https://www.amnesty.org/en/petition/stop-killer-robots/">https://www.amnesty.org/en/petition/stop-killer-robots/</a>
</div>
<div id="ref-toronto2018" class="csl-entry" role="listitem">
Amnesty International, &amp; Access Now. (2018, május 16). <em>The <span>Toronto</span> declaration: Protecting the rights to equality and non-discrimination in machine learning systems</em>. <a href="https://www.accessnow.org/the-toronto-declaration-protecting-the-rights-to-equality-and-non-discrimination-in-machine-learning-systems/">https://www.accessnow.org/the-toronto-declaration-protecting-the-rights-to-equality-and-non-discrimination-in-machine-learning-systems/</a>
</div>
<div id="ref-amodei2016" class="csl-entry" role="listitem">
Amodei, D., Olah, C., Steinhardt, J., Christiano, P., Schulman, J., &amp; Mané, D. (2016). <em>Concrete problems in <span>AI</span> safety</em>. <a href="https://arxiv.org/abs/1606.06565">https://arxiv.org/abs/1606.06565</a>
</div>
<div id="ref-arntz2016" class="csl-entry" role="listitem">
Arntz, M., Gregory, T., &amp; Zierahn, U. (2016). <em>The risk of automation for jobs in <span>OECD</span> countries: A comparative analysis</em> (OECD Social, Employment and Migration Working Papers No. 189). OECD Publishing. <a href="https://doi.org/10.1787/5jlz9h56dvq7-en">https://doi.org/10.1787/5jlz9h56dvq7-en</a>
</div>
<div id="ref-authorsguild2023" class="csl-entry" role="listitem">
Authors Guild. (2023, július 18). <em>Thousands of authors demand payment from <span>AI</span> companies for use of copyrighted works</em>. <a href="https://authorsguild.org/news/thousands-of-authors-demand-payment-from-ai-companies-for-use-of-copyrighted-works/">https://authorsguild.org/news/thousands-of-authors-demand-payment-from-ai-companies-for-use-of-copyrighted-works/</a>
</div>
<div id="ref-bender2021" class="csl-entry" role="listitem">
Bender, E. M., Gebru, T., McMillan-Major, A., &amp; Shmitchell, S. (2021). On the dangers of stochastic parrots: Can language models be too big? <em>Proceedings of the 2021 ACM Conference on Fairness, Accountability, and Transparency</em>, 610–623. <a href="https://doi.org/10.1145/3442188.3445922">https://doi.org/10.1145/3442188.3445922</a>
</div>
<div id="ref-bengio2023managing" class="csl-entry" role="listitem">
<span class="nocase">Bengio, Y., Hinton, G., Yao, A., Song, D., Abbeel, P., Harari, Y. N., és mtsai.</span> (2023). <em>Managing <span>AI</span> risks in an era of rapid progress</em>. <a href="https://arxiv.org/abs/2310.17688">https://arxiv.org/abs/2310.17688</a>
</div>
<div id="ref-wemustact2026" class="csl-entry" role="listitem">
Brynjolfsson, E., Agrawal, A., Korinek, A., &amp; Cunningham, T. (2026, július 13). <em>We must act now: A statement on <span>AI’s</span> transformation of the economy</em>. <a href="https://www.wemustactnow.ai/">https://www.wemustactnow.ai/</a>
</div>
<div id="ref-buolamwini2018" class="csl-entry" role="listitem">
Buolamwini, J., &amp; Gebru, T. (2018). Gender shades: Intersectional accuracy disparities in commercial gender classification. <em>Proceedings of the 1st Conference on Fairness, Accountability and Transparency, Proceedings of Machine Learning Research</em>, <em>81</em>, 77–91. <a href="https://proceedings.mlr.press/v81/buolamwini18a.html">https://proceedings.mlr.press/v81/buolamwini18a.html</a>
</div>
<div id="ref-butler1863" class="csl-entry" role="listitem">
Butler, S. (1863). Darwin among the machines. <em>The Press</em>. <a href="https://nzetc.victoria.ac.nz/tm/scholarly/tei-ButFir-t1-g1-t1-g1-t4-body.html">https://nzetc.victoria.ac.nz/tm/scholarly/tei-ButFir-t1-g1-t1-g1-t4-body.html</a>
</div>
<div id="ref-cbc2023" class="csl-entry" role="listitem">
CBC News. (2023, május 30). <em>Artificial intelligence poses <span>„risk of extinction,”</span> tech executives and scientists warn</em>. <a href="https://www.cbc.ca/news/world/artificial-intelligence-extinction-risk-1.6859118">https://www.cbc.ca/news/world/artificial-intelligence-extinction-risk-1.6859118</a>
</div>
<div id="ref-cais2023" class="csl-entry" role="listitem">
Center for AI Safety. (2023, május 30). <em>Statement on <span>AI</span> risk</em>. <a href="https://safe.ai/work/statement-on-ai-risk">https://safe.ai/work/statement-on-ai-risk</a>
</div>
<div id="ref-cnbc2018maven" class="csl-entry" role="listitem">
CNBC. (2018, április 4). <em>Google workers urge <span>CEO</span> <span>Sundar Pichai</span> to pull out of <span>Pentagon</span> project</em>. <a href="https://www.cnbc.com/2018/04/04/google-workers-urge-ceo-sundar-pichai-to-pull-out-of-pentagon-project.html">https://www.cnbc.com/2018/04/04/google-workers-urge-ceo-sundar-pichai-to-pull-out-of-pentagon-project.html</a>
</div>
<div id="ref-dw2023" class="csl-entry" role="listitem">
Deutsche Welle. (2023, május 30). <em>Top <span>AI</span> executives warn of <span>„risk of extinction”</span></em>. <a href="https://www.dw.com/en/top-ai-executives-warn-of-risk-of-extinction/a-65772574">https://www.dw.com/en/top-ai-executives-warn-of-risk-of-extinction/a-65772574</a>
</div>
<div id="ref-frey2013" class="csl-entry" role="listitem">
Frey, C. B., &amp; Osborne, M. A. (2013). <em>The future of employment: How susceptible are jobs to computerisation?</em> [Working paper]. Oxford Martin Programme on Technology; Employment. <a href="https://www.oxfordmartin.ox.ac.uk/downloads/academic/The_Future_of_Employment.pdf">https://www.oxfordmartin.ox.ac.uk/downloads/academic/The_Future_of_Employment.pdf</a>
</div>
<div id="ref-fli2015" class="csl-entry" role="listitem">
Future of Life Institute. (2015a). <em>Research priorities for robust and beneficial artificial intelligence: An open letter</em>. <a href="https://futureoflife.org/open-letter/ai-open-letter/">https://futureoflife.org/open-letter/ai-open-letter/</a>
</div>
<div id="ref-fli2015weapons" class="csl-entry" role="listitem">
Future of Life Institute. (2015b, július 28). <em>Autonomous weapons: An open letter from <span>AI</span> &amp; robotics researchers</em>. <a href="https://futureoflife.org/open-letter/open-letter-autonomous-weapons-ai-robotics/">https://futureoflife.org/open-letter/open-letter-autonomous-weapons-ai-robotics/</a>
</div>
<div id="ref-fli2017" class="csl-entry" role="listitem">
Future of Life Institute. (2017). <em>Asilomar <span>AI</span> principles</em>. <a href="https://futureoflife.org/open-letter/ai-principles/">https://futureoflife.org/open-letter/ai-principles/</a>
</div>
<div id="ref-fli2018pledge" class="csl-entry" role="listitem">
Future of Life Institute. (2018, július 18). <em>Lethal autonomous weapons pledge</em>. <a href="https://futureoflife.org/open-letter/lethal-autonomous-weapons-pledge/">https://futureoflife.org/open-letter/lethal-autonomous-weapons-pledge/</a>
</div>
<div id="ref-fli2023" class="csl-entry" role="listitem">
Future of Life Institute. (2023). <em>Pause giant <span>AI</span> experiments: An open letter</em>. <a href="https://futureoflife.org/open-letter/pause-giant-ai-experiments/">https://futureoflife.org/open-letter/pause-giant-ai-experiments/</a>
</div>
<div id="ref-dair2023" class="csl-entry" role="listitem">
Gebru, T., Bender, E. M., McMillan-Major, A., &amp; Mitchell, M. (2023, március 31). <em>Statement from the listed authors of <span>Stochastic Parrots</span> on the <span>„<span>AI</span> pause”</span> letter</em>. <a href="https://www.dair-institute.org/blog/letter-statement-March2023/">https://www.dair-institute.org/blog/letter-statement-March2023/</a>
</div>
<div id="ref-redlines2025" class="csl-entry" role="listitem">
Global Call for AI Red Lines. (2025, szeptember 22). <em>Global call for <span>AI</span> red lines</em>. <a href="https://red-lines.ai/">https://red-lines.ai/</a>
</div>
<div id="ref-gma2024" class="csl-entry" role="listitem">
Good Morning America. (2024, október 24). <em>Generative <span>AI</span> is disrupting creative communities; here is how they are fighting back</em>. <a href="https://www.goodmorningamerica.com/news/story/generative-ai-disrupting-creative-communities-fighting-back-115120318">https://www.goodmorningamerica.com/news/story/generative-ai-disrupting-creative-communities-fighting-back-115120318</a>
</div>
<div id="ref-hleg2019" class="csl-entry" role="listitem">
High-Level Expert Group on Artificial Intelligence. (2019). <em>Ethics guidelines for trustworthy <span>AI</span></em>. European Commission. <a href="https://digital-strategy.ec.europa.eu/en/library/ethics-guidelines-trustworthy-ai">https://digital-strategy.ec.europa.eu/en/library/ethics-guidelines-trustworthy-ai</a>
</div>
<div id="ref-ainow2023" class="csl-entry" role="listitem">
Kak, A., &amp; Myers West, S. (2023). <em>2023 landscape: Confronting tech power</em>. AI Now Institute. <a href="https://ainowinstitute.org/publication/2023-landscape">https://ainowinstitute.org/publication/2023-landscape</a>
</div>
<div id="ref-mandel2023" class="csl-entry" role="listitem">
Mandel, D. R. (2023). <em>Artificial general intelligence, existential risk, and human risk perception</em>. <a href="https://arxiv.org/abs/2311.08698">https://arxiv.org/abs/2311.08698</a>
</div>
<div id="ref-maslej2025" class="csl-entry" role="listitem">
<span class="nocase">Maslej, N. és mtsai.</span> (2025). <em>The <span>AI</span> index 2025 annual report</em>. Stanford Institute for Human-Centered Artificial Intelligence. <a href="https://hai.stanford.edu/ai-index/2025-ai-index-report">https://hai.stanford.edu/ai-index/2025-ai-index-report</a>
</div>
<div id="ref-mittr2017" class="csl-entry" role="listitem">
MIT Technology Review. (2017, augusztus 21). <em>Tech titans call to stamp out killer robots</em>. <a href="https://www.technologyreview.com/2017/08/21/149597/tech-titans-call-to-stamp-out-killer-robots/">https://www.technologyreview.com/2017/08/21/149597/tech-titans-call-to-stamp-out-killer-robots/</a>
</div>
<div id="ref-mittr2020" class="csl-entry" role="listitem">
MIT Technology Review. (2020, december 4). <em>We read the paper that forced <span>Timnit Gebru</span> out of <span>Google</span>. <span>Here’s</span> what it says</em>. <a href="https://www.technologyreview.com/2020/12/04/1013294/google-ai-ethics-research-paper-forced-out-timnit-gebru/">https://www.technologyreview.com/2020/12/04/1013294/google-ai-ethics-research-paper-forced-out-timnit-gebru/</a>
</div>
<div id="ref-mozilla2023" class="csl-entry" role="listitem">
Mozilla. (2023). <em>Joint statement on <span>AI</span> safety and openness</em>. <a href="https://open.mozilla.org/">https://open.mozilla.org/</a>
</div>
<div id="ref-musically2024" class="csl-entry" role="listitem">
Music Ally. (2024, október 23). <em>Over 13,000 creatives sign statement voicing <span>AI</span> concern</em>. <a href="https://musically.com/2024/10/23/over-13000-creatives-sign-statement-voicing-ai-concern/">https://musically.com/2024/10/23/over-13000-creatives-sign-statement-voicing-ai-concern/</a>
</div>
<div id="ref-muller2022" class="csl-entry" role="listitem">
Müller, V. C., &amp; Cannon, M. (2022). Existential risk from <span>AI</span> and orthogonality: Can we have it both ways? <em>Ratio</em>, <em>35</em>(1), 25–36. <a href="https://doi.org/10.1111/rati.12320">https://doi.org/10.1111/rati.12320</a>
</div>
<div id="ref-newtonrex2024" class="csl-entry" role="listitem">
Newton-Rex, E. (2024). <em>Statement on <span>AI</span> training</em>. <a href="https://www.aitrainingstatement.org/">https://www.aitrainingstatement.org/</a>
</div>
<div id="ref-oneil2016" class="csl-entry" role="listitem">
O’Neil, C. (2016). <em>Weapons of math destruction: How big data increases inequality and threatens democracy</em>. Crown.
</div>
<div id="ref-pal2020" class="csl-entry" role="listitem">
Pontifical Academy for Life. (2020, február 28). <em>Rome call for <span>AI</span> ethics</em>. <a href="https://www.vatican.va/roman_curia/pontifical_academies/acdlife/documents/rc_pont-acd_life_doc_20202228_rome-call-for-ai-ethics_en.html">https://www.vatican.va/roman_curia/pontifical_academies/acdlife/documents/rc_pont-acd_life_doc_20202228_rome-call-for-ai-ethics_en.html</a>
</div>
<div id="ref-reclaimyourface2021" class="csl-entry" role="listitem">
Reclaim Your Face. (2021). <em>Reclaim your face: European citizens’ initiative to ban biometric mass surveillance</em>. <a href="https://reclaimyourface.eu/">https://reclaimyourface.eu/</a>
</div>
<div id="ref-aiid" class="csl-entry" role="listitem">
Responsible AI Collaborative. (é. n.). <em><span>AI</span> incident database</em>. Elérés <a href="https://incidentdatabase.ai/">https://incidentdatabase.ai/</a>
</div>
<div id="ref-reuters2020pope" class="csl-entry" role="listitem">
Reuters. (2020a, február 28). <em>Pope to endorse principles on <span>AI</span> ethics with <span>Microsoft</span>, <span>IBM</span></em>. <a href="https://www.reuters.com/article/technology/pope-to-endorse-principles-on-ai-ethics-with-microsoft-ibm-idUSL2N2AS01S/">https://www.reuters.com/article/technology/pope-to-endorse-principles-on-ai-ethics-with-microsoft-ibm-idUSL2N2AS01S/</a>
</div>
<div id="ref-reuters2020gebru" class="csl-entry" role="listitem">
Reuters. (2020b, december 4). <em>Top <span>AI</span> ethics researcher says <span>Google</span> fired her; company denies it</em>. <a href="https://www.reuters.com/article/technology/top-ai-ethics-researcher-says-google-fired-her-company-denies-it-idUSKBN28E2QE/">https://www.reuters.com/article/technology/top-ai-ethics-researcher-says-google-fired-her-company-denies-it-idUSKBN28E2QE/</a>
</div>
<div id="ref-reuters2023extinction" class="csl-entry" role="listitem">
Reuters. (2023a, május 30). <em>Top <span>AI</span> <span>CEOs</span>, experts raise <span>„risk of extinction”</span> from <span>AI</span></em>. <a href="https://www.reuters.com/technology/top-ai-ceos-experts-raise-risk-extinction-ai-2023-05-30/">https://www.reuters.com/technology/top-ai-ceos-experts-raise-risk-extinction-ai-2023-05-30/</a>
</div>
<div id="ref-reuters2023actors" class="csl-entry" role="listitem">
Reuters. (2023b, július 21). <em>Actors decry <span>„existential crisis”</span> over <span>AI</span>-generated synthetic actors</em>. <a href="https://www.reuters.com/technology/actors-decry-existential-crisis-over-ai-generated-synthetic-actors-2023-07-21/">https://www.reuters.com/technology/actors-decry-existential-crisis-over-ai-generated-synthetic-actors-2023-07-21/</a>
</div>
<div id="ref-reuters2023safeguards" class="csl-entry" role="listitem">
Reuters. (2023c, november 9). <em>Hollywood actors secure safeguards around <span>AI</span> use on screen</em>. <a href="https://www.reuters.com/business/media-telecom/hollywood-actors-secure-safeguards-around-ai-use-screen-2023-11-09/">https://www.reuters.com/business/media-telecom/hollywood-actors-secure-safeguards-around-ai-use-screen-2023-11-09/</a>
</div>
<div id="ref-romecall2020" class="csl-entry" role="listitem">
Rome Call for AI Ethics. (2020). <em>The call</em>. <a href="https://www.romecall.org/the-call/">https://www.romecall.org/the-call/</a>
</div>
<div id="ref-russell2015" class="csl-entry" role="listitem">
Russell, S., Dewey, D., &amp; Tegmark, M. (2015). Research priorities for robust and beneficial artificial intelligence. <em>AI Magazine</em>, <em>36</em>(4), 105–114. <a href="https://doi.org/10.1609/aimag.v36i4.2577">https://doi.org/10.1609/aimag.v36i4.2577</a>
</div>
<div id="ref-sagaftra2023" class="csl-entry" role="listitem">
SAG-AFTRA. (2023). <em>2023 <span>TV</span>/theatrical contracts</em>. <a href="https://www.sagaftra.org/contracts-industry-resources/contracts/2023-tvtheatrical-contracts">https://www.sagaftra.org/contracts-industry-resources/contracts/2023-tvtheatrical-contracts</a>
</div>
<div id="ref-stone2016" class="csl-entry" role="listitem">
<span class="nocase">Stone, P., Brooks, R., Brynjolfsson, E., Calo, R., Etzioni, O., Hager, G., és mtsai.</span> (2016). <em>Artificial intelligence and life in 2030: One hundred year study on artificial intelligence. <span>Report</span> of the 2015–2016 study panel</em>. Stanford University. <a href="https://ai100.stanford.edu/2016-report">https://ai100.stanford.edu/2016-report</a>
</div>
<div id="ref-skr_policy" class="csl-entry" role="listitem">
Stop Killer Robots. (é. n.-a). <em>Our policy position</em>. Elérés <a href="https://www.stopkillerrobots.org/our-policies/">https://www.stopkillerrobots.org/our-policies/</a>
</div>
<div id="ref-skr_facts" class="csl-entry" role="listitem">
Stop Killer Robots. (é. n.-b). <em>Problems with autonomous weapons</em>. Elérés <a href="https://www.stopkillerrobots.org/stop-killer-robots/facts-about-autonomous-weapons/">https://www.stopkillerrobots.org/stop-killer-robots/facts-about-autonomous-weapons/</a>
</div>
<div id="ref-skr_home" class="csl-entry" role="listitem">
Stop Killer Robots. (é. n.-c). <em>Stop killer robots</em>. Elérés <a href="https://www.stopkillerrobots.org/">https://www.stopkillerrobots.org/</a>
</div>
<div id="ref-techcrunch2026pentagon" class="csl-entry" role="listitem">
TechCrunch. (2026, február 27). <em>Employees at <span>Google</span> and <span>OpenAI</span> support <span>Anthropic’s</span> <span>Pentagon</span> stand in open letter</em>. <a href="https://techcrunch.com/2026/02/27/employees-at-google-and-openai-support-anthropics-pentagon-stand-in-open-letter/">https://techcrunch.com/2026/02/27/employees-at-google-and-openai-support-anthropics-pentagon-stand-in-open-letter/</a>
</div>
<div id="ref-artnewspaper2024" class="csl-entry" role="listitem">
The Art Newspaper. (2024, október 24). <em>Thousands sign statement against <span>AI</span> content scraping</em>. <a href="https://www.theartnewspaper.com/2024/10/24/artists-statement-opposing-artificial-intelligence-content-scraping">https://www.theartnewspaper.com/2024/10/24/artists-statement-opposing-artificial-intelligence-content-scraping</a>
</div>
<div id="ref-verge2020" class="csl-entry" role="listitem">
The Verge. (2020, december 5). <em>Timnit Gebru’s actual paper may explain why <span>Google</span> ejected her</em>. <a href="https://www.theverge.com/2020/12/5/22155985/paper-timnit-gebru-fired-google-large-language-models-search-ai">https://www.theverge.com/2020/12/5/22155985/paper-timnit-gebru-fired-google-large-language-models-search-ai</a>
</div>
<div id="ref-turing1950" class="csl-entry" role="listitem">
Turing, A. M. (1950). Computing machinery and intelligence. <em>Mind</em>, <em>59</em>(236), 433–460. <a href="https://doi.org/10.1093/mind/LIX.236.433">https://doi.org/10.1093/mind/LIX.236.433</a>
</div>
<div id="ref-ukgov2023" class="csl-entry" role="listitem">
UK Government. (2023, november 1). <em>The <span>Bletchley</span> declaration by countries attending the <span>AI</span> safety summit, 1–2 <span>November</span> 2023</em>. <a href="https://www.gov.uk/government/publications/ai-safety-summit-2023-the-bletchley-declaration">https://www.gov.uk/government/publications/ai-safety-summit-2023-the-bletchley-declaration</a>
</div>
<div id="ref-montreal2018" class="csl-entry" role="listitem">
Université de Montréal. (2018, december 4). <em>Montréal declaration for a responsible development of artificial intelligence</em>. <a href="https://montrealdeclaration-responsibleai.com/">https://montrealdeclaration-responsibleai.com/</a>
</div>
<div id="ref-ainow2018" class="csl-entry" role="listitem">
<span class="nocase">Whittaker, M., Crawford, K., Dobbe, R., Fried, G., Kaziunas, E., Mathur, V., és mtsai.</span> (2018). <em><span>AI Now</span> report 2018</em>. AI Now Institute, New York University. <a href="https://ainowinstitute.org/publication/ai-now-2018-report-2">https://ainowinstitute.org/publication/ai-now-2018-report-2</a>
</div>
<div id="ref-wiener1960" class="csl-entry" role="listitem">
Wiener, N. (1960). Some moral and technical consequences of automation. <em>Science</em>, <em>131</em>(3410), 1355–1358. <a href="https://doi.org/10.1126/science.131.3410.1355">https://doi.org/10.1126/science.131.3410.1355</a>
</div>
<div id="ref-wiener1988" class="csl-entry" role="listitem">
Wiener, N. (1988). <em>The human use of human beings: Cybernetics and society</em>. Da Capo Press. (Original work published 1950)
</div>
<div id="ref-wired2021" class="csl-entry" role="listitem">
Wired. (2021, június 8). <em>What really happened when <span>Google</span> ousted <span>Timnit Gebru</span></em>. <a href="https://www.wired.com/story/google-timnit-gebru-ai-what-really-happened/">https://www.wired.com/story/google-timnit-gebru-ai-what-really-happened/</a>
</div>
<div id="ref-wga2023" class="csl-entry" role="listitem">
Writers Guild of America. (2023). <em>Summary of the 2023 <span>WGA</span> <span>MBA</span></em>. <a href="https://www.wgacontract2023.org/the-campaign/summary-of-the-2023-wga-mba">https://www.wgacontract2023.org/the-campaign/summary-of-the-2023-wga-mba</a>
</div>
<div id="ref-yudkowsky2008" class="csl-entry" role="listitem">
Yudkowsky, E. (2008). Artificial intelligence as a positive and negative factor in global risk. In N. Bostrom &amp; M. M. Ćirković (Szerk.), <em>Global catastrophic risks</em> (o. 308–345). Oxford University Press. <a href="https://intelligence.org/files/AIPosNegFactor.pdf">https://intelligence.org/files/AIPosNegFactor.pdf</a>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./tokenek-es-kreditek.html" class="pagination-link" aria-label="Tokenek, kontextus és kreditek: mitől fogy el a chatbot?">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Tokenek, kontextus és kreditek: mitől fogy el a chatbot?</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./MI-kockazat-monitoring.html" class="pagination-link" aria-label="MI-kockázatok, figyelmeztetések és cselekvési felhívások folyamatos monitorozása">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">MI-kockázatok, figyelmeztetések és cselekvési felhívások folyamatos monitorozása</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>